import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

/// Icon entry with IconData and its name for search
class IconEntry {
  final IconData icon;
  final String name;

  IconEntry({required this.icon, required this.name});
}

/// Helper function to create IconEntry
IconEntry iconEntry(IconData icon, String name) {
  return IconEntry(icon: icon, name: name);
}

/// Icon category with name and icons
class IconCategory {
  final String name;
  final IconData categoryIcon;
  final List<IconEntry> icons;

  IconCategory({
    required this.name,
    required this.categoryIcon,
    required this.icons,
  });
}

/// Comprehensive icon collection - 2500+ icons from Material & Font Awesome
class ComprehensiveIconData {
  static final List<IconCategory> categories = [
    // WORK & BUSINESS (200+ icons)
    IconCategory(
      name: 'Work',
      categoryIcon: Icons.work_rounded,
      icons: [
        // Material
        iconEntry(Icons.work_rounded, 'work job'),
        iconEntry(Icons.business_rounded, 'business company'),
        iconEntry(Icons.folder_rounded, 'folder directory'),
        iconEntry(Icons.folder_open_rounded, 'folder open'),
        iconEntry(Icons.description_rounded, 'description document'),
        iconEntry(Icons.article_rounded, 'article document'),
        iconEntry(Icons.note_rounded, 'note'),
        iconEntry(Icons.assignment_rounded, 'assignment task'),
        iconEntry(Icons.task_rounded, 'task todo'),
        iconEntry(Icons.checklist_rounded, 'checklist'),
        iconEntry(Icons.check_circle_rounded, 'check done'),
        iconEntry(Icons.meeting_room_rounded, 'meeting room'),
        iconEntry(Icons.business_center_rounded, 'business center'),
        // Font Awesome
        iconEntry(FontAwesomeIcons.briefcase, 'briefcase work'),
        iconEntry(FontAwesomeIcons.suitcase, 'suitcase travel'),
        iconEntry(FontAwesomeIcons.building, 'building office'),
        iconEntry(FontAwesomeIcons.buildingUser, 'building user office'),
        iconEntry(FontAwesomeIcons.industry, 'industry factory'),
        iconEntry(FontAwesomeIcons.warehouse, 'warehouse storage'),
        iconEntry(FontAwesomeIcons.fileLines, 'file lines document'),
        iconEntry(FontAwesomeIcons.fileContract, 'file contract legal'),
        iconEntry(FontAwesomeIcons.fileInvoice, 'file invoice'),
        iconEntry(FontAwesomeIcons.filePdf, 'pdf document file'),
        iconEntry(FontAwesomeIcons.fileWord, 'word document file'),
        iconEntry(FontAwesomeIcons.fileExcel, 'excel spreadsheet file'),
        iconEntry(FontAwesomeIcons.filePowerpoint, 'powerpoint presentation file'),
        iconEntry(FontAwesomeIcons.fileCode, 'file code programming'),
        iconEntry(FontAwesomeIcons.fileArchive, 'file archive zip'),
        iconEntry(FontAwesomeIcons.folderOpen, 'folder open directory'),
        iconEntry(FontAwesomeIcons.folderClosed, 'folder closed directory'),
        iconEntry(FontAwesomeIcons.folderTree, 'folder tree structure'),
        iconEntry(FontAwesomeIcons.clipboardList, 'clipboard list'),
        iconEntry(FontAwesomeIcons.clipboardCheck, 'clipboard check done'),
        iconEntry(FontAwesomeIcons.tasks, 'tasks checklist todo'),
        iconEntry(FontAwesomeIcons.listCheck, 'list check done'),
        iconEntry(FontAwesomeIcons.squareCheck, 'square check done'),
        iconEntry(FontAwesomeIcons.circleCheck, 'circle check done'),
        iconEntry(FontAwesomeIcons.handshake, 'handshake deal partnership'),
        iconEntry(FontAwesomeIcons.addressCard, 'address card contact'),
        iconEntry(FontAwesomeIcons.idCard, 'id card identity'),
        iconEntry(FontAwesomeIcons.idBadge, 'id badge identity'),
        iconEntry(FontAwesomeIcons.userTie, 'user tie professional'),
        iconEntry(FontAwesomeIcons.users, 'users team people'),
        iconEntry(FontAwesomeIcons.peopleGroup, 'people group team'),
        iconEntry(FontAwesomeIcons.userGroup, 'user group team'),
        iconEntry(FontAwesomeIcons.userGear, 'user gear settings'),
        iconEntry(FontAwesomeIcons.chartLine, 'chart line graph analytics'),
        iconEntry(FontAwesomeIcons.chartPie, 'chart pie graph analytics'),
        iconEntry(FontAwesomeIcons.chartBar, 'chart bar graph analytics'),
        iconEntry(FontAwesomeIcons.chartArea, 'chart area graph analytics'),
        iconEntry(FontAwesomeIcons.chartColumn, 'chart column graph'),
        iconEntry(FontAwesomeIcons.chartSimple, 'chart simple graph'),
        iconEntry(FontAwesomeIcons.chartGantt, 'chart gantt project'),
        iconEntry(FontAwesomeIcons.calculator, 'calculator math'),
        iconEntry(FontAwesomeIcons.percentage, 'percentage math'),
        iconEntry(FontAwesomeIcons.dollarSign, 'dollar money currency'),
        iconEntry(FontAwesomeIcons.euroSign, 'euro money currency'),
        iconEntry(FontAwesomeIcons.sterlingSign, 'pound sterling money currency'),
        iconEntry(FontAwesomeIcons.indianRupeeSign, 'rupee money currency'),
        iconEntry(FontAwesomeIcons.yenSign, 'yen money currency'),
        iconEntry(FontAwesomeIcons.bitcoinSign, 'bitcoin crypto currency'),
        iconEntry(FontAwesomeIcons.moneyBill, 'money bill cash'),
        iconEntry(FontAwesomeIcons.moneyBills, 'money bills cash'),
        iconEntry(FontAwesomeIcons.moneyBillTransfer, 'money bill transfer'),
        iconEntry(FontAwesomeIcons.moneyBillTrendUp, 'money bill trend up'),
        iconEntry(FontAwesomeIcons.moneyCheck, 'money check'),
        iconEntry(FontAwesomeIcons.moneyCheckDollar, 'money check dollar'),
        iconEntry(FontAwesomeIcons.coins, 'coins money change'),
        iconEntry(FontAwesomeIcons.creditCard, 'credit card payment'),
        iconEntry(FontAwesomeIcons.wallet, 'wallet money'),
        iconEntry(FontAwesomeIcons.cashRegister, 'cash register'),
        iconEntry(FontAwesomeIcons.receipt, 'receipt bill'),
        iconEntry(FontAwesomeIcons.stamp, 'stamp official approval'),
        iconEntry(FontAwesomeIcons.balanceScale, 'balance scale justice law'),
        iconEntry(FontAwesomeIcons.gavel, 'gavel judge law court'),
        iconEntry(FontAwesomeIcons.landmark, 'landmark government'),
        iconEntry(FontAwesomeIcons.buildingColumns, 'building columns bank'),
        iconEntry(FontAwesomeIcons.university, 'university education'),
        iconEntry(FontAwesomeIcons.graduationCap, 'graduation cap education'),
        iconEntry(FontAwesomeIcons.award, 'award achievement trophy'),
        iconEntry(FontAwesomeIcons.trophy, 'trophy award achievement'),
        iconEntry(FontAwesomeIcons.medal, 'medal award achievement'),
        iconEntry(FontAwesomeIcons.certificate, 'certificate achievement'),
        iconEntry(FontAwesomeIcons.ribbon, 'ribbon achievement'),
        iconEntry(FontAwesomeIcons.projectDiagram, 'project diagram flowchart'),
        iconEntry(FontAwesomeIcons.sitemap, 'sitemap hierarchy structure'),
        iconEntry(FontAwesomeIcons.networkWired, 'network wired connection'),
        iconEntry(FontAwesomeIcons.print, 'print printer'),
        iconEntry(FontAwesomeIcons.fax, 'fax machine'),
        iconEntry(FontAwesomeIcons.phone, 'phone call'),
        iconEntry(FontAwesomeIcons.phoneFlip, 'phone flip call'),
        iconEntry(FontAwesomeIcons.phoneVolume, 'phone volume call'),
        iconEntry(FontAwesomeIcons.envelopeOpen, 'envelope open email'),
        iconEntry(FontAwesomeIcons.envelope, 'envelope email mail'),
        iconEntry(FontAwesomeIcons.inbox, 'inbox mail'),
        iconEntry(FontAwesomeIcons.paperPlane, 'paper plane send'),
        iconEntry(FontAwesomeIcons.pen, 'pen write edit'),
        iconEntry(FontAwesomeIcons.pencil, 'pencil write edit'),
        iconEntry(FontAwesomeIcons.penToSquare, 'pen to square edit'),
        iconEntry(FontAwesomeIcons.highlighter, 'highlighter mark'),
        iconEntry(FontAwesomeIcons.marker, 'marker highlight'),
        iconEntry(FontAwesomeIcons.stapler, 'stapler office'),
        iconEntry(FontAwesomeIcons.paperclip, 'paperclip attach'),
        iconEntry(FontAwesomeIcons.thumbtack, 'thumbtack pin'),
        iconEntry(FontAwesomeIcons.magnifyingGlass, 'magnifying glass search'),
        iconEntry(FontAwesomeIcons.magnifyingGlassPlus, 'magnifying glass plus zoom in'),
        iconEntry(FontAwesomeIcons.magnifyingGlassMinus, 'magnifying glass minus zoom out'),
        iconEntry(FontAwesomeIcons.laptop, 'laptop computer'),
        iconEntry(FontAwesomeIcons.desktopAlt, 'desktop computer'),
        iconEntry(FontAwesomeIcons.tablet, 'tablet device'),
        iconEntry(FontAwesomeIcons.mobileAlt, 'mobile phone device'),
        iconEntry(FontAwesomeIcons.keyboard, 'keyboard computer'),
        iconEntry(FontAwesomeIcons.mouse, 'mouse computer'),
        iconEntry(FontAwesomeIcons.server, 'server computer'),
        iconEntry(FontAwesomeIcons.database, 'database storage'),
        iconEntry(FontAwesomeIcons.hardDrive, 'hard drive storage'),
        iconEntry(FontAwesomeIcons.cloudArrowUp, 'cloud arrow up upload'),
        iconEntry(FontAwesomeIcons.cloudArrowDown, 'cloud arrow down download'),
        iconEntry(FontAwesomeIcons.wifi, 'wifi internet'),
        iconEntry(FontAwesomeIcons.ethernet, 'ethernet network'),
        iconEntry(FontAwesomeIcons.signal, 'signal connection'),
        iconEntry(FontAwesomeIcons.rss, 'rss feed'),
        iconEntry(FontAwesomeIcons.qrcode, 'qr code'),
        iconEntry(FontAwesomeIcons.barcode, 'barcode scan'),
      ],
    ),

    // TIME & SCHEDULE (80+ icons)
    IconCategory(
      name: 'Time',
      categoryIcon: Icons.schedule_rounded,
      icons: [
        // Material
        iconEntry(Icons.today_rounded, 'today calendar'),
        iconEntry(Icons.calendar_today_rounded, 'calendar today'),
        iconEntry(Icons.event_rounded, 'event calendar'),
        iconEntry(Icons.schedule_rounded, 'schedule time clock'),
        iconEntry(Icons.access_time_rounded, 'access time clock'),
        iconEntry(Icons.alarm_rounded, 'alarm clock'),
        iconEntry(Icons.timer_rounded, 'timer stopwatch'),
        iconEntry(Icons.hourglass_empty_rounded, 'hourglass empty'),
        iconEntry(Icons.hourglass_full_rounded, 'hourglass full'),
        iconEntry(Icons.watch_later_rounded, 'watch later time'),
        iconEntry(Icons.update_rounded, 'update refresh'),
        iconEntry(Icons.history_rounded, 'history time'),
        iconEntry(Icons.access_alarm_rounded, 'access alarm clock'),
        iconEntry(Icons.alarm_add_rounded, 'alarm add'),
        iconEntry(Icons.alarm_on_rounded, 'alarm on'),
        iconEntry(Icons.alarm_off_rounded, 'alarm off'),
        // Font Awesome
        iconEntry(FontAwesomeIcons.clock, 'clock time'),
        iconEntry(FontAwesomeIcons.stopwatch, 'stopwatch timer'),
        iconEntry(FontAwesomeIcons.stopwatch20, 'stopwatch 20 timer'),
        iconEntry(FontAwesomeIcons.calendar, 'calendar date'),
        iconEntry(FontAwesomeIcons.calendarDays, 'calendar days'),
        iconEntry(FontAwesomeIcons.calendarWeek, 'calendar week'),
        iconEntry(FontAwesomeIcons.calendarDay, 'calendar day'),
        iconEntry(FontAwesomeIcons.calendarCheck, 'calendar check done'),
        iconEntry(FontAwesomeIcons.calendarPlus, 'calendar plus add'),
        iconEntry(FontAwesomeIcons.calendarMinus, 'calendar minus remove'),
        iconEntry(FontAwesomeIcons.calendarXmark, 'calendar xmark cancel'),
        iconEntry(FontAwesomeIcons.hourglass, 'hourglass time'),
        iconEntry(FontAwesomeIcons.hourglassStart, 'hourglass start'),
        iconEntry(FontAwesomeIcons.hourglassHalf, 'hourglass half'),
        iconEntry(FontAwesomeIcons.hourglassEnd, 'hourglass end'),
        iconEntry(FontAwesomeIcons.bell, 'bell notification alarm'),
        iconEntry(FontAwesomeIcons.bellSlash, 'bell slash mute'),
        iconEntry(FontAwesomeIcons.clockRotateLeft, 'clock rotate left history'),
        iconEntry(FontAwesomeIcons.arrowRotateRight, 'arrow rotate right refresh'),
        iconEntry(FontAwesomeIcons.arrowRotateLeft, 'arrow rotate left undo'),
        iconEntry(FontAwesomeIcons.sun, 'sun day morning'),
        iconEntry(FontAwesomeIcons.moon, 'moon night evening'),
        iconEntry(FontAwesomeIcons.cloudSun, 'cloud sun day'),
        iconEntry(FontAwesomeIcons.cloudMoon, 'cloud moon night'),
      ],
    ),

    // HEALTH & FITNESS (150+ icons)
    IconCategory(
      name: 'Health',
      categoryIcon: Icons.favorite_rounded,
      icons: [
        // Material
        iconEntry(Icons.fitness_center_rounded, 'fitness center gym'),
        iconEntry(Icons.sports_gymnastics_rounded, 'sports gymnastics'),
        iconEntry(Icons.directions_run_rounded, 'directions run running'),
        iconEntry(Icons.directions_walk_rounded, 'directions walk walking'),
        iconEntry(Icons.directions_bike_rounded, 'directions bike bicycle'),
        iconEntry(Icons.pool_rounded, 'pool swimming'),
        iconEntry(Icons.sports_tennis_rounded, 'sports tennis'),
        iconEntry(Icons.sports_basketball_rounded, 'sports basketball'),
        iconEntry(Icons.sports_soccer_rounded, 'sports soccer football'),
        iconEntry(Icons.sports_football_rounded, 'sports football'),
        iconEntry(Icons.local_hospital_rounded, 'local hospital medical'),
        iconEntry(Icons.medical_services_rounded, 'medical services'),
        iconEntry(Icons.medication_rounded, 'medication medicine'),
        iconEntry(Icons.favorite_rounded, 'favorite heart love'),
        iconEntry(Icons.health_and_safety_rounded, 'health and safety'),
        // Font Awesome
        iconEntry(FontAwesomeIcons.heartPulse, 'heart pulse health'),
        iconEntry(FontAwesomeIcons.heart, 'heart love health'),
        iconEntry(FontAwesomeIcons.dumbbell, 'dumbbell gym workout'),
        iconEntry(FontAwesomeIcons.personRunning, 'person running exercise'),
        iconEntry(FontAwesomeIcons.personWalking, 'person walking exercise'),
        iconEntry(FontAwesomeIcons.personBiking, 'person biking cycling'),
        iconEntry(FontAwesomeIcons.personSwimming, 'person swimming'),
        iconEntry(FontAwesomeIcons.personHiking, 'person hiking'),
        iconEntry(FontAwesomeIcons.personSkiing, 'person skiing'),
        iconEntry(FontAwesomeIcons.personSkating, 'person skating'),
        iconEntry(FontAwesomeIcons.personSnowboarding, 'person snowboarding'),
        iconEntry(FontAwesomeIcons.baseball, 'baseball sport'),
        iconEntry(FontAwesomeIcons.basketball, 'basketball sport'),
        iconEntry(FontAwesomeIcons.football, 'football sport'),
        iconEntry(FontAwesomeIcons.futbol, 'futbol soccer'),
        iconEntry(FontAwesomeIcons.volleyball, 'volleyball sport'),
        iconEntry(FontAwesomeIcons.tableTennisPaddleBall, 'table tennis sport'),
        iconEntry(FontAwesomeIcons.bowlingBall, 'bowling sport'),
        iconEntry(FontAwesomeIcons.golfBall, 'golf ball sport'),
        iconEntry(FontAwesomeIcons.hockeyPuck, 'hockey puck sport'),
        iconEntry(FontAwesomeIcons.hospital, 'hospital medical'),
        iconEntry(FontAwesomeIcons.houseMedical, 'house medical'),
        iconEntry(FontAwesomeIcons.kitMedical, 'kit medical first aid'),
        iconEntry(FontAwesomeIcons.briefcaseMedical, 'briefcase medical'),
        iconEntry(FontAwesomeIcons.userDoctor, 'user doctor physician'),
        iconEntry(FontAwesomeIcons.userNurse, 'user nurse medical'),
        iconEntry(FontAwesomeIcons.stethoscope, 'stethoscope medical'),
        iconEntry(FontAwesomeIcons.syringe, 'syringe injection medical'),
        iconEntry(FontAwesomeIcons.pills, 'pills medication'),
        iconEntry(FontAwesomeIcons.prescription, 'prescription medical'),
        iconEntry(FontAwesomeIcons.prescriptionBottle, 'prescription bottle'),
        iconEntry(FontAwesomeIcons.prescriptionBottleMedical, 'prescription bottle medical'),
        iconEntry(FontAwesomeIcons.thermometer, 'thermometer temperature'),
        iconEntry(FontAwesomeIcons.bandage, 'bandage medical'),
        iconEntry(FontAwesomeIcons.xRay, 'x-ray medical'),
        iconEntry(FontAwesomeIcons.heartCirclePlus, 'heart circle plus add'),
        iconEntry(FontAwesomeIcons.heartCircleCheck, 'heart circle check'),
        iconEntry(FontAwesomeIcons.lungs, 'lungs medical'),
        iconEntry(FontAwesomeIcons.brain, 'brain mental health'),
        iconEntry(FontAwesomeIcons.tooth, 'tooth dental'),
        iconEntry(FontAwesomeIcons.eye, 'eye vision'),
        iconEntry(FontAwesomeIcons.eyeDropper, 'eye dropper medical'),
        iconEntry(FontAwesomeIcons.hand, 'hand'),
        iconEntry(FontAwesomeIcons.spa, 'spa wellness'),
        iconEntry(FontAwesomeIcons.droplet, 'droplet water'),
        iconEntry(FontAwesomeIcons.fire, 'fire energy'),
        iconEntry(FontAwesomeIcons.bed, 'bed sleep rest'),
        iconEntry(FontAwesomeIcons.handHoldingHeart, 'hand holding heart care'),
        iconEntry(FontAwesomeIcons.personPraying, 'person praying meditation'),
        iconEntry(FontAwesomeIcons.leaf, 'leaf natural organic'),
        iconEntry(FontAwesomeIcons.seedling, 'seedling growth plant'),
        iconEntry(FontAwesomeIcons.appleWhole, 'apple whole fruit'),
        iconEntry(FontAwesomeIcons.carrot, 'carrot vegetable'),
        iconEntry(FontAwesomeIcons.bottleWater, 'bottle water hydration'),
        iconEntry(FontAwesomeIcons.weight, 'weight scale'),
        iconEntry(FontAwesomeIcons.scaleBalanced, 'scale balanced'),
        iconEntry(FontAwesomeIcons.personArrowUpFromLine, 'person arrow up growth'),
        iconEntry(FontAwesomeIcons.children, 'children kids family'),
        iconEntry(FontAwesomeIcons.baby, 'baby infant'),
        iconEntry(FontAwesomeIcons.babyCarriage, 'baby carriage stroller'),
        iconEntry(FontAwesomeIcons.smoking, 'smoking cigarette'),
        iconEntry(FontAwesomeIcons.smokingBan, 'smoking ban no smoking'),
        iconEntry(FontAwesomeIcons.wheelchair, 'wheelchair accessibility'),
        iconEntry(FontAwesomeIcons.crutch, 'crutch medical'),
        iconEntry(FontAwesomeIcons.personCane, 'person cane walking stick'),
        iconEntry(FontAwesomeIcons.glasses, 'glasses vision'),
        iconEntry(FontAwesomeIcons.lowVision, 'low vision accessibility'),
        iconEntry(FontAwesomeIcons.deaf, 'deaf hearing accessibility'),
        iconEntry(FontAwesomeIcons.signLanguage, 'sign language accessibility'),
        iconEntry(FontAwesomeIcons.braille, 'braille accessibility'),
      ],
    ),

    // FOOD & DINING (100+ icons)
    IconCategory(
      name: 'Food',
      categoryIcon: Icons.restaurant_rounded,
      icons: [
        // Material
        iconEntry(Icons.restaurant_rounded, 'restaurant dining'),
        iconEntry(Icons.restaurant_menu_rounded, 'restaurant menu'),
        iconEntry(Icons.local_dining_rounded, 'local dining food'),
        iconEntry(Icons.fastfood_rounded, 'fast food'),
        iconEntry(Icons.set_meal_rounded, 'set meal food'),
        iconEntry(Icons.breakfast_dining_rounded, 'breakfast dining'),
        iconEntry(Icons.lunch_dining_rounded, 'lunch dining'),
        iconEntry(Icons.dinner_dining_rounded, 'dinner dining'),
        iconEntry(Icons.local_cafe_rounded, 'local cafe coffee'),
        iconEntry(Icons.local_bar_rounded, 'local bar drinks'),
        iconEntry(Icons.local_pizza_rounded, 'local pizza'),
        iconEntry(Icons.icecream_rounded, 'ice cream dessert'),
        iconEntry(Icons.cake_rounded, 'cake dessert'),
        iconEntry(Icons.coffee_rounded, 'coffee drink'),
        // Font Awesome
        iconEntry(FontAwesomeIcons.utensils, 'utensils fork spoon'),
        iconEntry(FontAwesomeIcons.bowlFood, 'bowl food'),
        iconEntry(FontAwesomeIcons.bowlRice, 'bowl rice food'),
        iconEntry(FontAwesomeIcons.burger, 'burger hamburger fast food'),
        iconEntry(FontAwesomeIcons.pizzaSlice, 'pizza slice'),
        iconEntry(FontAwesomeIcons.hotdog, 'hotdog food'),
        iconEntry(FontAwesomeIcons.breadSlice, 'bread slice'),
        iconEntry(FontAwesomeIcons.cheese, 'cheese food dairy'),
        iconEntry(FontAwesomeIcons.bacon, 'bacon food'),
        iconEntry(FontAwesomeIcons.drumstickBite, 'drumstick bite chicken'),
        iconEntry(FontAwesomeIcons.egg, 'egg food'),
        iconEntry(FontAwesomeIcons.fishFins, 'fish fins seafood'),
        iconEntry(FontAwesomeIcons.shrimp, 'shrimp seafood'),
        iconEntry(FontAwesomeIcons.lemon, 'lemon fruit'),
        iconEntry(FontAwesomeIcons.pepperHot, 'pepper hot vegetable'),
        iconEntry(FontAwesomeIcons.stroopwafel, 'stroopwafel dessert'),
        iconEntry(FontAwesomeIcons.cakeCandles, 'cake candles birthday'),
        iconEntry(FontAwesomeIcons.cookie, 'cookie dessert'),
        iconEntry(FontAwesomeIcons.candyCane, 'candy cane sweet'),
        iconEntry(FontAwesomeIcons.iceCream, 'ice cream dessert'),
        iconEntry(FontAwesomeIcons.mugHot, 'mug hot coffee tea'),
        iconEntry(FontAwesomeIcons.mugSaucer, 'mug saucer cup'),
        iconEntry(FontAwesomeIcons.coffee, 'coffee drink'),
        iconEntry(FontAwesomeIcons.wineGlass, 'wine glass drink'),
        iconEntry(FontAwesomeIcons.wineBottle, 'wine bottle drink'),
        iconEntry(FontAwesomeIcons.champagneGlasses, 'champagne glasses celebrate'),
        iconEntry(FontAwesomeIcons.martiniGlass, 'martini glass cocktail'),
        iconEntry(FontAwesomeIcons.beerMugEmpty, 'beer mug empty drink'),
        iconEntry(FontAwesomeIcons.bottleDroplet, 'bottle droplet water'),
        iconEntry(FontAwesomeIcons.glassWater, 'glass water drink'),
        iconEntry(FontAwesomeIcons.blender, 'blender kitchen'),
        iconEntry(FontAwesomeIcons.kitchenSet, 'kitchen set cooking'),
        iconEntry(FontAwesomeIcons.jar, 'jar container'),
        iconEntry(FontAwesomeIcons.utensils, 'utensils cutlery dining'),
        iconEntry(FontAwesomeIcons.mortarPestle, 'mortar pestle kitchen'),
        iconEntry(FontAwesomeIcons.fire, 'fire flame cooking'),
        iconEntry(FontAwesomeIcons.temperatureHalf, 'temperature half cooking'),
      ],
    ),

    // EDUCATION & LEARNING (90+ icons)
    IconCategory(
      name: 'Education',
      categoryIcon: Icons.school_rounded,
      icons: [
        // Material
        iconEntry(Icons.school_rounded, 'school education'),
        iconEntry(Icons.book_rounded, 'book read'),
        iconEntry(Icons.library_books_rounded, 'library books'),
        iconEntry(Icons.menu_book_rounded, 'menu book read'),
        iconEntry(Icons.auto_stories_rounded, 'auto stories book'),
        iconEntry(Icons.class_rounded, 'class education'),
        iconEntry(Icons.bookmark_rounded, 'bookmark save'),
        iconEntry(Icons.bookmarks_rounded, 'bookmarks save'),
        iconEntry(Icons.collections_bookmark_rounded, 'collections bookmark'),
        // Font Awesome
        iconEntry(FontAwesomeIcons.book, 'book read'),
        iconEntry(FontAwesomeIcons.bookOpen, 'book open read'),
        iconEntry(FontAwesomeIcons.bookBookmark, 'book bookmark'),
        iconEntry(FontAwesomeIcons.bookAtlas, 'book atlas geography'),
        iconEntry(FontAwesomeIcons.bookBible, 'book bible religious'),
        iconEntry(FontAwesomeIcons.bookJournalWhills, 'book journal'),
        iconEntry(FontAwesomeIcons.bookMedical, 'book medical'),
        iconEntry(FontAwesomeIcons.bookQuran, 'book quran religious'),
        iconEntry(FontAwesomeIcons.bookSkull, 'book skull'),
        iconEntry(FontAwesomeIcons.bookTanakh, 'book tanakh religious'),
        iconEntry(FontAwesomeIcons.userGraduate, 'user graduate student'),
        iconEntry(FontAwesomeIcons.chalkboard, 'chalkboard teaching'),
        iconEntry(FontAwesomeIcons.chalkboardUser, 'chalkboard user teaching'),
        iconEntry(FontAwesomeIcons.school, 'school education'),
        iconEntry(FontAwesomeIcons.personChalkboard, 'person chalkboard teaching'),
        iconEntry(FontAwesomeIcons.pencil, 'pencil write'),
        iconEntry(FontAwesomeIcons.pen, 'pen write'),
        iconEntry(FontAwesomeIcons.penClip, 'pen clip write'),
        iconEntry(FontAwesomeIcons.penFancy, 'pen fancy write'),
        iconEntry(FontAwesomeIcons.penNib, 'pen nib write'),
        iconEntry(FontAwesomeIcons.penRuler, 'pen ruler design'),
        iconEntry(FontAwesomeIcons.eraser, 'eraser delete'),
        iconEntry(FontAwesomeIcons.ruler, 'ruler measure'),
        iconEntry(FontAwesomeIcons.rulerCombined, 'ruler combined measure'),
        iconEntry(FontAwesomeIcons.rulerHorizontal, 'ruler horizontal measure'),
        iconEntry(FontAwesomeIcons.rulerVertical, 'ruler vertical measure'),
        iconEntry(FontAwesomeIcons.compass, 'compass navigation'),
        iconEntry(FontAwesomeIcons.compassDrafting, 'compass drafting design'),
        iconEntry(FontAwesomeIcons.squareRootVariable, 'square root variable math'),
        iconEntry(FontAwesomeIcons.calculator, 'calculator math'),
        iconEntry(FontAwesomeIcons.flask, 'flask science'),
        iconEntry(FontAwesomeIcons.flaskVial, 'flask vial science'),
        iconEntry(FontAwesomeIcons.microscope, 'microscope science'),
        iconEntry(FontAwesomeIcons.atom, 'atom science physics'),
        iconEntry(FontAwesomeIcons.dna, 'dna science biology'),
        iconEntry(FontAwesomeIcons.vial, 'vial science'),
        iconEntry(FontAwesomeIcons.vialCircleCheck, 'vial circle check science'),
        iconEntry(FontAwesomeIcons.vialVirus, 'vial virus science'),
        iconEntry(FontAwesomeIcons.magnifyingGlass, 'magnifying glass search'),
        iconEntry(FontAwesomeIcons.globe, 'globe world earth'),
        iconEntry(FontAwesomeIcons.earthAmericas, 'earth americas geography'),
        iconEntry(FontAwesomeIcons.earthAfrica, 'earth africa geography'),
        iconEntry(FontAwesomeIcons.earthAsia, 'earth asia geography'),
        iconEntry(FontAwesomeIcons.earthEurope, 'earth europe geography'),
        iconEntry(FontAwesomeIcons.earthOceania, 'earth oceania geography'),
        iconEntry(FontAwesomeIcons.mapLocationDot, 'map location dot geography'),
        iconEntry(FontAwesomeIcons.map, 'map geography'),
        iconEntry(FontAwesomeIcons.lightbulb, 'lightbulb idea'),
        iconEntry(FontAwesomeIcons.brain, 'brain thinking learning'),
        iconEntry(FontAwesomeIcons.palette, 'palette art'),
        iconEntry(FontAwesomeIcons.paintbrush, 'paintbrush art'),
        iconEntry(FontAwesomeIcons.music, 'music audio'),
        iconEntry(FontAwesomeIcons.guitar, 'guitar music'),
        iconEntry(FontAwesomeIcons.drum, 'drum music'),
      ],
    ),

    // HOME & HOUSEHOLD (80+ icons)
    IconCategory(
      name: 'Home',
      categoryIcon: Icons.home_rounded,
      icons: [
        // Material
        iconEntry(Icons.home_rounded, 'home house'),
        iconEntry(Icons.home_work_rounded, 'home work'),
        iconEntry(Icons.house_rounded, 'house home'),
        iconEntry(Icons.cleaning_services_rounded, 'cleaning services'),
        iconEntry(Icons.wash_rounded, 'wash laundry'),
        iconEntry(Icons.bed_rounded, 'bed sleep'),
        iconEntry(Icons.kitchen_rounded, 'kitchen'),
        iconEntry(Icons.bathroom_rounded, 'bathroom'),
        iconEntry(Icons.shower_rounded, 'shower'),
        // Font Awesome
        iconEntry(FontAwesomeIcons.house, 'house home'),
        iconEntry(FontAwesomeIcons.houseChimney, 'house chimney home'),
        iconEntry(FontAwesomeIcons.houseUser, 'house user home'),
        iconEntry(FontAwesomeIcons.houseLaptop, 'house laptop remote work'),
        iconEntry(FontAwesomeIcons.couch, 'couch sofa furniture'),
        iconEntry(FontAwesomeIcons.bed, 'bed sleep'),
        iconEntry(FontAwesomeIcons.chair, 'chair furniture'),
        iconEntry(FontAwesomeIcons.doorOpen, 'door open entrance'),
        iconEntry(FontAwesomeIcons.doorClosed, 'door closed entrance'),
        iconEntry(FontAwesomeIcons.stairs, 'stairs'),
        iconEntry(FontAwesomeIcons.elevator, 'elevator lift'),
        iconEntry(FontAwesomeIcons.kitchenSet, 'kitchen set cooking'),
        iconEntry(FontAwesomeIcons.sink, 'sink bathroom kitchen'),
        iconEntry(FontAwesomeIcons.toilet, 'toilet bathroom'),
        iconEntry(FontAwesomeIcons.shower, 'shower bathroom'),
        iconEntry(FontAwesomeIcons.bath, 'bath bathtub'),
        iconEntry(FontAwesomeIcons.soap, 'soap cleaning'),
        iconEntry(FontAwesomeIcons.pumpSoap, 'pump soap cleaning'),
        iconEntry(FontAwesomeIcons.broom, 'broom cleaning sweep'),
        iconEntry(FontAwesomeIcons.sprayCan, 'spray can cleaning'),
        iconEntry(FontAwesomeIcons.faucet, 'faucet tap water'),
        iconEntry(FontAwesomeIcons.faucetDrip, 'faucet drip leak'),
        iconEntry(FontAwesomeIcons.plug, 'plug electric'),
        iconEntry(FontAwesomeIcons.lightbulb, 'light bulb lamp'),
        iconEntry(FontAwesomeIcons.fan, 'fan cooling'),
        iconEntry(FontAwesomeIcons.fire, 'fire heating'),
        iconEntry(FontAwesomeIcons.temperatureArrowUp, 'temperature arrow up hot'),
        iconEntry(FontAwesomeIcons.temperatureArrowDown, 'temperature arrow down cold'),
        iconEntry(FontAwesomeIcons.temperatureHalf, 'temperature half'),
        iconEntry(FontAwesomeIcons.snowflake, 'snowflake cold cooling'),
        iconEntry(FontAwesomeIcons.icicles, 'icicles cold'),
        iconEntry(FontAwesomeIcons.key, 'key lock'),
        iconEntry(FontAwesomeIcons.lock, 'lock security'),
        iconEntry(FontAwesomeIcons.lockOpen, 'lock open unlock'),
        iconEntry(FontAwesomeIcons.shirt, 'shirt clothes'),
        iconEntry(FontAwesomeIcons.socks, 'socks clothes'),
        iconEntry(FontAwesomeIcons.mitten, 'mitten clothes winter'),
        iconEntry(FontAwesomeIcons.personDress, 'person dress clothes'),
        iconEntry(FontAwesomeIcons.vest, 'vest clothes'),
        iconEntry(FontAwesomeIcons.rug, 'rug carpet floor'),
        iconEntry(FontAwesomeIcons.paintRoller, 'paint roller renovation'),
        iconEntry(FontAwesomeIcons.hammer, 'hammer tool'),
        iconEntry(FontAwesomeIcons.screwdriver, 'screwdriver tool'),
        iconEntry(FontAwesomeIcons.wrench, 'wrench tool'),
        iconEntry(FontAwesomeIcons.screwdriverWrench, 'screwdriver wrench tools'),
        iconEntry(FontAwesomeIcons.toolbox, 'toolbox tools'),
      ],
    ),

    // ENTERTAINMENT & MEDIA (120+ icons)
    IconCategory(
      name: 'Entertainment',
      categoryIcon: Icons.movie_rounded,
      icons: [
        // Material
        iconEntry(Icons.movie_rounded, 'movie film cinema'),
        iconEntry(Icons.theaters_rounded, 'theaters cinema'),
        iconEntry(Icons.local_movies_rounded, 'local movies cinema'),
        iconEntry(Icons.videocam_rounded, 'video camera'),
        iconEntry(Icons.music_note_rounded, 'music note'),
        iconEntry(Icons.headset_rounded, 'headset audio'),
        iconEntry(Icons.audiotrack_rounded, 'audio track music'),
        iconEntry(Icons.album_rounded, 'album music'),
        iconEntry(Icons.radio_rounded, 'radio'),
        iconEntry(Icons.tv_rounded, 'tv television'),
        iconEntry(Icons.gamepad_rounded, 'gamepad gaming'),
        iconEntry(Icons.sports_esports_rounded, 'sports esports gaming'),
        // Font Awesome
        iconEntry(FontAwesomeIcons.film, 'film movie'),
        iconEntry(FontAwesomeIcons.clapperboard, 'clapperboard movie film'),
        iconEntry(FontAwesomeIcons.video, 'video camera'),
        iconEntry(FontAwesomeIcons.videoSlash, 'video slash camera off'),
        iconEntry(FontAwesomeIcons.camera, 'camera photo'),
        iconEntry(FontAwesomeIcons.cameraRetro, 'camera retro photo'),
        iconEntry(FontAwesomeIcons.cameraRotate, 'camera rotate flip'),
        iconEntry(FontAwesomeIcons.image, 'image photo picture'),
        iconEntry(FontAwesomeIcons.images, 'images photos pictures'),
        iconEntry(FontAwesomeIcons.photoFilm, 'photo film media'),
        iconEntry(FontAwesomeIcons.music, 'music audio'),
        iconEntry(FontAwesomeIcons.headphones, 'headphones audio'),
        iconEntry(FontAwesomeIcons.headset, 'headset audio'),
        iconEntry(FontAwesomeIcons.microphone, 'microphone audio'),
        iconEntry(FontAwesomeIcons.microphoneSlash, 'microphone slash mute'),
        iconEntry(FontAwesomeIcons.volumeHigh, 'volume high loud'),
        iconEntry(FontAwesomeIcons.volumeLow, 'volume low quiet'),
        iconEntry(FontAwesomeIcons.volumeOff, 'volume off mute'),
        iconEntry(FontAwesomeIcons.volumeXmark, 'volume xmark mute'),
        iconEntry(FontAwesomeIcons.play, 'play media'),
        iconEntry(FontAwesomeIcons.pause, 'pause media'),
        iconEntry(FontAwesomeIcons.stop, 'stop media'),
        iconEntry(FontAwesomeIcons.forward, 'forward media'),
        iconEntry(FontAwesomeIcons.backward, 'backward media'),
        iconEntry(FontAwesomeIcons.forwardStep, 'forward step media next'),
        iconEntry(FontAwesomeIcons.backwardStep, 'backward step media previous'),
        iconEntry(FontAwesomeIcons.forwardFast, 'forward fast media'),
        iconEntry(FontAwesomeIcons.backwardFast, 'backward fast media'),
        iconEntry(FontAwesomeIcons.repeat, 'repeat loop media'),
        iconEntry(FontAwesomeIcons.shuffle, 'shuffle random media'),
        iconEntry(FontAwesomeIcons.eject, 'eject media'),
        iconEntry(FontAwesomeIcons.circlePlay, 'circle play media'),
        iconEntry(FontAwesomeIcons.circlePause, 'circle pause media'),
        iconEntry(FontAwesomeIcons.circleStop, 'circle stop media'),
        iconEntry(FontAwesomeIcons.tv, 'tv television'),
        iconEntry(FontAwesomeIcons.radio, 'radio'),
        iconEntry(FontAwesomeIcons.podcast, 'podcast audio'),
        iconEntry(FontAwesomeIcons.rss, 'rss feed'),
        iconEntry(FontAwesomeIcons.satellite, 'satellite signal'),
        iconEntry(FontAwesomeIcons.satelliteDish, 'satellite dish signal'),
        iconEntry(FontAwesomeIcons.broadcastTower, 'broadcast tower signal'),
        iconEntry(FontAwesomeIcons.gamepad, 'gamepad gaming'),
        iconEntry(FontAwesomeIcons.dice, 'dice game'),
        iconEntry(FontAwesomeIcons.diceOne, 'dice one game'),
        iconEntry(FontAwesomeIcons.diceTwo, 'dice two game'),
        iconEntry(FontAwesomeIcons.diceThree, 'dice three game'),
        iconEntry(FontAwesomeIcons.diceFour, 'dice four game'),
        iconEntry(FontAwesomeIcons.diceFive, 'dice five game'),
        iconEntry(FontAwesomeIcons.diceSix, 'dice six game'),
        iconEntry(FontAwesomeIcons.chessPawn, 'chess pawn game'),
        iconEntry(FontAwesomeIcons.chessKnight, 'chess knight game'),
        iconEntry(FontAwesomeIcons.chessBishop, 'chess bishop game'),
        iconEntry(FontAwesomeIcons.chessRook, 'chess rook game'),
        iconEntry(FontAwesomeIcons.chessQueen, 'chess queen game'),
        iconEntry(FontAwesomeIcons.chessKing, 'chess king game'),
        iconEntry(FontAwesomeIcons.chessBoard, 'chess board game'),
        iconEntry(FontAwesomeIcons.puzzlePiece, 'puzzle piece game'),
        iconEntry(FontAwesomeIcons.paintbrush, 'paintbrush art'),
        iconEntry(FontAwesomeIcons.palette, 'palette art'),
        iconEntry(FontAwesomeIcons.brush, 'brush art'),
        iconEntry(FontAwesomeIcons.pen, 'pen art'),
        iconEntry(FontAwesomeIcons.pencil, 'pencil art draw'),
        iconEntry(FontAwesomeIcons.masksTheater, 'masks theater drama'),
        iconEntry(FontAwesomeIcons.guitar, 'guitar music'),
        iconEntry(FontAwesomeIcons.drum, 'drum music'),
        iconEntry(FontAwesomeIcons.drumSteelpan, 'drum steelpan music'),
        iconEntry(FontAwesomeIcons.ticket, 'ticket event'),
        iconEntry(FontAwesomeIcons.ticketSimple, 'ticket simple event'),
        iconEntry(FontAwesomeIcons.theaterMasks, 'theater masks drama'),
      ],
    ),

    // TRAVEL & TRANSPORTATION (100+ icons)
    IconCategory(
      name: 'Travel',
      categoryIcon: Icons.flight_rounded,
      icons: [
        // Material
        iconEntry(Icons.flight_rounded, 'flight airplane'),
        iconEntry(Icons.flight_takeoff_rounded, 'flight takeoff airplane'),
        iconEntry(Icons.flight_land_rounded, 'flight land airplane'),
        iconEntry(Icons.local_airport_rounded, 'local airport'),
        iconEntry(Icons.directions_car_rounded, 'directions car vehicle'),
        iconEntry(Icons.directions_bus_rounded, 'directions bus'),
        iconEntry(Icons.directions_subway_rounded, 'directions subway metro'),
        iconEntry(Icons.directions_train_rounded, 'directions train'),
        iconEntry(Icons.directions_boat_rounded, 'directions boat ship'),
        iconEntry(Icons.hotel_rounded, 'hotel accommodation'),
        iconEntry(Icons.luggage_rounded, 'luggage suitcase'),
        // Font Awesome
        iconEntry(FontAwesomeIcons.plane, 'plane airplane'),
        iconEntry(FontAwesomeIcons.planeDeparture, 'plane departure takeoff'),
        iconEntry(FontAwesomeIcons.planeArrival, 'plane arrival landing'),
        iconEntry(FontAwesomeIcons.planeUp, 'plane up flying'),
        iconEntry(FontAwesomeIcons.helicopter, 'helicopter aircraft'),
        iconEntry(FontAwesomeIcons.jetFighter, 'jet fighter plane'),
        iconEntry(FontAwesomeIcons.car, 'car vehicle automobile'),
        iconEntry(FontAwesomeIcons.carSide, 'car side vehicle'),
        iconEntry(FontAwesomeIcons.carRear, 'car rear vehicle'),
        iconEntry(FontAwesomeIcons.taxi, 'taxi cab vehicle'),
        iconEntry(FontAwesomeIcons.bus, 'bus vehicle'),
        iconEntry(FontAwesomeIcons.busSimple, 'bus simple vehicle'),
        iconEntry(FontAwesomeIcons.vanShuttle, 'van shuttle vehicle'),
        iconEntry(FontAwesomeIcons.truck, 'truck vehicle'),
        iconEntry(FontAwesomeIcons.truckPickup, 'truck pickup vehicle'),
        iconEntry(FontAwesomeIcons.truckFast, 'truck fast delivery'),
        iconEntry(FontAwesomeIcons.truckMoving, 'truck moving relocation'),
        iconEntry(FontAwesomeIcons.caravan, 'caravan rv vehicle'),
        iconEntry(FontAwesomeIcons.trailer, 'trailer vehicle'),
        iconEntry(FontAwesomeIcons.motorcycle, 'motorcycle bike vehicle'),
        iconEntry(FontAwesomeIcons.bicycle, 'bicycle bike vehicle'),
        iconEntry(FontAwesomeIcons.train, 'train railway'),
        iconEntry(FontAwesomeIcons.trainSubway, 'train subway metro'),
        iconEntry(FontAwesomeIcons.trainTram, 'train tram streetcar'),
        iconEntry(FontAwesomeIcons.ship, 'ship boat vessel'),
        iconEntry(FontAwesomeIcons.ferry, 'ferry boat'),
        iconEntry(FontAwesomeIcons.sailboat, 'sailboat boat'),
        iconEntry(FontAwesomeIcons.anchor, 'anchor ship boat'),
        iconEntry(FontAwesomeIcons.rocket, 'rocket space'),
        iconEntry(FontAwesomeIcons.shuttleSpace, 'shuttle space spacecraft'),
        iconEntry(FontAwesomeIcons.suitcase, 'suitcase luggage'),
        iconEntry(FontAwesomeIcons.suitcaseRolling, 'suitcase rolling luggage'),
        iconEntry(FontAwesomeIcons.passport, 'passport travel document'),
        iconEntry(FontAwesomeIcons.idCard, 'id card identity'),
        iconEntry(FontAwesomeIcons.mapLocationDot, 'map location dot navigation'),
        iconEntry(FontAwesomeIcons.map, 'map navigation'),
        iconEntry(FontAwesomeIcons.mapMarked, 'map marked navigation'),
        iconEntry(FontAwesomeIcons.compass, 'compass navigation'),
        iconEntry(FontAwesomeIcons.locationDot, 'location dot place'),
        iconEntry(FontAwesomeIcons.locationPin, 'location pin place'),
        iconEntry(FontAwesomeIcons.locationCrosshairs, 'location crosshairs gps'),
        iconEntry(FontAwesomeIcons.route, 'route path navigation'),
        iconEntry(FontAwesomeIcons.road, 'road street'),
        iconEntry(FontAwesomeIcons.roadBarrier, 'road barrier construction'),
        iconEntry(FontAwesomeIcons.trafficLight, 'traffic light signal'),
        iconEntry(FontAwesomeIcons.gasPump, 'gas pump station fuel'),
        iconEntry(FontAwesomeIcons.chargingStation, 'charging station electric'),
        iconEntry(FontAwesomeIcons.hotel, 'hotel accommodation'),
        iconEntry(FontAwesomeIcons.bed, 'bed hotel'),
        iconEntry(FontAwesomeIcons.tent, 'tent camping'),
        iconEntry(FontAwesomeIcons.campground, 'campground camping'),
        iconEntry(FontAwesomeIcons.carBattery, 'car battery vehicle'),
        iconEntry(FontAwesomeIcons.oilCan, 'oil can vehicle'),
        iconEntry(FontAwesomeIcons.gaugeHigh, 'gauge high speedometer'),
        iconEntry(FontAwesomeIcons.parking, 'parking'),
        iconEntry(FontAwesomeIcons.squareParking, 'square parking'),
        iconEntry(FontAwesomeIcons.mountain, 'mountain nature'),
        iconEntry(FontAwesomeIcons.personHiking, 'person hiking outdoor'),
        iconEntry(FontAwesomeIcons.personSwimming, 'person swimming beach'),
        iconEntry(FontAwesomeIcons.umbrellaBeach, 'umbrella beach vacation'),
        iconEntry(FontAwesomeIcons.ticket, 'ticket event travel'),
        iconEntry(FontAwesomeIcons.globe, 'globe world travel'),
      ],
    ),

    // COMMUNICATION & SOCIAL (100+ icons)
    IconCategory(
      name: 'Social',
      categoryIcon: Icons.chat_rounded,
      icons: [
        // Material
        iconEntry(Icons.chat_rounded, 'chat message'),
        iconEntry(Icons.message_rounded, 'message chat'),
        iconEntry(Icons.forum_rounded, 'forum discussion'),
        iconEntry(Icons.comment_rounded, 'comment feedback'),
        iconEntry(Icons.chat_bubble_rounded, 'chat bubble message'),
        iconEntry(Icons.textsms_rounded, 'text sms message'),
        iconEntry(Icons.email_rounded, 'email mail'),
        iconEntry(Icons.phone_rounded, 'phone call'),
        iconEntry(Icons.videocam_rounded, 'video cam call'),
        iconEntry(Icons.person_rounded, 'person user'),
        iconEntry(Icons.people_rounded, 'people users group'),
        iconEntry(Icons.group_rounded, 'group team people'),
        iconEntry(Icons.contacts_rounded, 'contacts people'),
        // Font Awesome
        iconEntry(FontAwesomeIcons.comment, 'comment message'),
        iconEntry(FontAwesomeIcons.commentDots, 'comment dots chat'),
        iconEntry(FontAwesomeIcons.commentMedical, 'comment medical message'),
        iconEntry(FontAwesomeIcons.commentSlash, 'comment slash no message'),
        iconEntry(FontAwesomeIcons.comments, 'comments messages chat'),
        iconEntry(FontAwesomeIcons.message, 'message chat'),
        iconEntry(FontAwesomeIcons.envelope, 'envelope email mail'),
        iconEntry(FontAwesomeIcons.envelopeOpen, 'envelope open email mail'),
        iconEntry(FontAwesomeIcons.envelopeCircleCheck, 'envelope circle check sent'),
        iconEntry(FontAwesomeIcons.inbox, 'inbox mail'),
        iconEntry(FontAwesomeIcons.at, 'at email mention'),
        iconEntry(FontAwesomeIcons.phone, 'phone call'),
        iconEntry(FontAwesomeIcons.phoneFlip, 'phone flip call'),
        iconEntry(FontAwesomeIcons.phoneVolume, 'phone volume call'),
        iconEntry(FontAwesomeIcons.phoneSlash, 'phone slash no call'),
        iconEntry(FontAwesomeIcons.video, 'video call camera'),
        iconEntry(FontAwesomeIcons.videoSlash, 'video slash no camera'),
        iconEntry(FontAwesomeIcons.user, 'user person'),
        iconEntry(FontAwesomeIcons.userPlus, 'user plus add person'),
        iconEntry(FontAwesomeIcons.userMinus, 'user minus remove person'),
        iconEntry(FontAwesomeIcons.userCheck, 'user check verified person'),
        iconEntry(FontAwesomeIcons.userXmark, 'user xmark block person'),
        iconEntry(FontAwesomeIcons.userClock, 'user clock person time'),
        iconEntry(FontAwesomeIcons.userGear, 'user gear settings person'),
        iconEntry(FontAwesomeIcons.userLock, 'user lock secure person'),
        iconEntry(FontAwesomeIcons.userShield, 'user shield protect person'),
        iconEntry(FontAwesomeIcons.users, 'users people group'),
        iconEntry(FontAwesomeIcons.usersBetweenLines, 'users between lines group'),
        iconEntry(FontAwesomeIcons.usersGear, 'users gear group settings'),
        iconEntry(FontAwesomeIcons.usersLine, 'users line group'),
        iconEntry(FontAwesomeIcons.usersRectangle, 'users rectangle group'),
        iconEntry(FontAwesomeIcons.usersSlash, 'users slash no group'),
        iconEntry(FontAwesomeIcons.userGroup, 'user group team'),
        iconEntry(FontAwesomeIcons.peopleGroup, 'people group team'),
        iconEntry(FontAwesomeIcons.thumbsUp, 'thumbs up like approve'),
        iconEntry(FontAwesomeIcons.thumbsDown, 'thumbs down dislike'),
        iconEntry(FontAwesomeIcons.heart, 'heart love favorite'),
        iconEntry(FontAwesomeIcons.star, 'star favorite rating'),
        iconEntry(FontAwesomeIcons.share, 'share social'),
        iconEntry(FontAwesomeIcons.shareNodes, 'share nodes social network'),
        iconEntry(FontAwesomeIcons.shareFromSquare, 'share from square export'),
        iconEntry(FontAwesomeIcons.retweet, 'retweet share'),
        iconEntry(FontAwesomeIcons.reply, 'reply respond'),
        iconEntry(FontAwesomeIcons.replyAll, 'reply all respond'),
        iconEntry(FontAwesomeIcons.paperPlane, 'paper plane send'),
        iconEntry(FontAwesomeIcons.bullhorn, 'bullhorn announce'),
        iconEntry(FontAwesomeIcons.rss, 'rss feed'),
        iconEntry(FontAwesomeIcons.rssSquare, 'rss square feed'),
        iconEntry(FontAwesomeIcons.hashtag, 'hashtag tag'),
        iconEntry(FontAwesomeIcons.at, 'at mention'),
        iconEntry(FontAwesomeIcons.link, 'link url'),
        iconEntry(FontAwesomeIcons.linkSlash, 'link slash unlink'),
        iconEntry(FontAwesomeIcons.globe, 'globe world internet'),
        iconEntry(FontAwesomeIcons.wifi, 'wifi internet'),
        iconEntry(FontAwesomeIcons.signal, 'signal connection'),
        iconEntry(FontAwesomeIcons.bell, 'bell notification'),
        iconEntry(FontAwesomeIcons.bellSlash, 'bell slash mute notification'),
        iconEntry(FontAwesomeIcons.addressBook, 'address book contacts'),
        iconEntry(FontAwesomeIcons.idCard, 'id card identity contact'),
        iconEntry(FontAwesomeIcons.idBadge, 'id badge identity contact'),
        iconEntry(FontAwesomeIcons.locationDot, 'location dot place'),
        iconEntry(FontAwesomeIcons.earthAmericas, 'earth americas world'),
        iconEntry(FontAwesomeIcons.language, 'language translate'),
        // Social Media Icons
        iconEntry(FontAwesomeIcons.facebook, 'facebook social media'),
        iconEntry(FontAwesomeIcons.twitter, 'twitter social media'),
        iconEntry(FontAwesomeIcons.instagram, 'instagram social media'),
        iconEntry(FontAwesomeIcons.linkedin, 'linkedin social media'),
        iconEntry(FontAwesomeIcons.youtube, 'youtube social media'),
        iconEntry(FontAwesomeIcons.tiktok, 'tiktok social media'),
        iconEntry(FontAwesomeIcons.whatsapp, 'whatsapp messaging'),
        iconEntry(FontAwesomeIcons.telegram, 'telegram messaging'),
        iconEntry(FontAwesomeIcons.discord, 'discord social media'),
        iconEntry(FontAwesomeIcons.slack, 'slack communication'),
        iconEntry(FontAwesomeIcons.skype, 'skype communication'),
        iconEntry(FontAwesomeIcons.reddit, 'reddit social media'),
        iconEntry(FontAwesomeIcons.snapchat, 'snapchat social media'),
        iconEntry(FontAwesomeIcons.pinterest, 'pinterest social media'),
        iconEntry(FontAwesomeIcons.tumblr, 'tumblr social media'),
      ],
    ),

    // NATURE & WEATHER (80+ icons)
    IconCategory(
      name: 'Nature',
      categoryIcon: Icons.park_rounded,
      icons: [
        // Material
        iconEntry(Icons.park_rounded, 'park nature tree'),
        iconEntry(Icons.forest_rounded, 'forest trees nature'),
        iconEntry(Icons.yard_rounded, 'yard garden nature'),
        iconEntry(Icons.grass_rounded, 'grass nature lawn'),
        iconEntry(Icons.local_florist_rounded, 'local florist flower'),
        iconEntry(Icons.wb_sunny_rounded, 'wb sunny sun weather'),
        iconEntry(Icons.nightlight_rounded, 'nightlight moon weather'),
        iconEntry(Icons.cloud_rounded, 'cloud weather'),
        iconEntry(Icons.umbrella_rounded, 'umbrella rain weather'),
        iconEntry(Icons.ac_unit_rounded, 'ac unit snow weather'),
        iconEntry(Icons.water_rounded, 'water nature'),
        iconEntry(Icons.water_drop_rounded, 'water drop rain'),
        iconEntry(Icons.pets_rounded, 'pets animals'),
        // Font Awesome
        iconEntry(FontAwesomeIcons.tree, 'tree nature forest'),
        iconEntry(FontAwesomeIcons.seedling, 'seedling plant nature'),
        iconEntry(FontAwesomeIcons.leaf, 'leaf nature plant'),
        iconEntry(FontAwesomeIcons.spa, 'spa nature wellness'),
        iconEntry(FontAwesomeIcons.clover, 'clover plant nature'),
        iconEntry(FontAwesomeIcons.sun, 'sun weather day'),
        iconEntry(FontAwesomeIcons.moon, 'moon weather night'),
        iconEntry(FontAwesomeIcons.cloudSun, 'cloud sun weather'),
        iconEntry(FontAwesomeIcons.cloudMoon, 'cloud moon weather'),
        iconEntry(FontAwesomeIcons.cloud, 'cloud weather'),
        iconEntry(FontAwesomeIcons.cloudRain, 'cloud rain weather'),
        iconEntry(FontAwesomeIcons.cloudShowersHeavy, 'cloud showers heavy rain weather'),
        iconEntry(FontAwesomeIcons.cloudBolt, 'cloud bolt thunder weather'),
        iconEntry(FontAwesomeIcons.cloudMeatball, 'cloud meatball weather'),
        iconEntry(FontAwesomeIcons.snowflake, 'snowflake snow weather'),
        iconEntry(FontAwesomeIcons.icicles, 'icicles cold weather'),
        iconEntry(FontAwesomeIcons.temperatureHigh, 'temperature high hot weather'),
        iconEntry(FontAwesomeIcons.temperatureLow, 'temperature low cold weather'),
        iconEntry(FontAwesomeIcons.wind, 'wind weather'),
        iconEntry(FontAwesomeIcons.tornado, 'tornado weather'),
        iconEntry(FontAwesomeIcons.hurricane, 'hurricane weather'),
        iconEntry(FontAwesomeIcons.rainbow, 'rainbow weather nature'),
        iconEntry(FontAwesomeIcons.meteor, 'meteor space'),
        iconEntry(FontAwesomeIcons.starAndCrescent, 'star and crescent moon'),
        iconEntry(FontAwesomeIcons.umbrellaBeach, 'umbrella beach summer'),
        iconEntry(FontAwesomeIcons.mountain, 'mountain nature'),
        iconEntry(FontAwesomeIcons.mountainSun, 'mountain sun nature'),
        iconEntry(FontAwesomeIcons.volcano, 'volcano nature'),
        iconEntry(FontAwesomeIcons.water, 'water nature'),
        iconEntry(FontAwesomeIcons.droplet, 'droplet water rain'),
        iconEntry(FontAwesomeIcons.fire, 'fire nature element'),
        iconEntry(FontAwesomeIcons.bug, 'bug insect nature'),
        iconEntry(FontAwesomeIcons.spider, 'spider insect nature'),
        iconEntry(FontAwesomeIcons.worm, 'worm insect nature'),
        iconEntry(FontAwesomeIcons.frog, 'frog animal nature'),
        iconEntry(FontAwesomeIcons.fish, 'fish animal nature'),
        iconEntry(FontAwesomeIcons.fishFins, 'fish fins animal nature'),
        iconEntry(FontAwesomeIcons.shrimp, 'shrimp animal nature'),
        iconEntry(FontAwesomeIcons.otter, 'otter animal nature'),
        iconEntry(FontAwesomeIcons.dog, 'dog pet animal'),
        iconEntry(FontAwesomeIcons.cat, 'cat pet animal'),
        iconEntry(FontAwesomeIcons.horse, 'horse animal'),
        iconEntry(FontAwesomeIcons.horseHead, 'horse head animal'),
        iconEntry(FontAwesomeIcons.cow, 'cow animal'),
        iconEntry(FontAwesomeIcons.hippo, 'hippo animal'),
        iconEntry(FontAwesomeIcons.dragon, 'dragon mythical animal'),
        iconEntry(FontAwesomeIcons.dove, 'dove bird animal'),
        iconEntry(FontAwesomeIcons.crow, 'crow bird animal'),
        iconEntry(FontAwesomeIcons.feather, 'feather bird'),
        iconEntry(FontAwesomeIcons.paw, 'paw pet animal'),
        iconEntry(FontAwesomeIcons.kiwiBird, 'kiwi bird animal'),
        iconEntry(FontAwesomeIcons.locust, 'locust insect'),
        iconEntry(FontAwesomeIcons.mosquito, 'mosquito insect'),
      ],
    ),

    // SHOPPING & COMMERCE (70+ icons)
    IconCategory(
      name: 'Shopping',
      categoryIcon: Icons.shopping_cart_rounded,
      icons: [
        // Material
        iconEntry(Icons.shopping_cart_rounded, 'shopping cart'),
        iconEntry(Icons.shopping_bag_rounded, 'shopping bag'),
        iconEntry(Icons.shopping_basket_rounded, 'shopping basket'),
        iconEntry(Icons.local_grocery_store_rounded, 'local grocery store'),
        iconEntry(Icons.store_rounded, 'store shop'),
        iconEntry(Icons.storefront_rounded, 'storefront shop'),
        iconEntry(Icons.local_mall_rounded, 'local mall shopping'),
        iconEntry(Icons.local_offer_rounded, 'local offer sale'),
        iconEntry(Icons.sell_rounded, 'sell price tag'),
        iconEntry(Icons.discount_rounded, 'discount sale'),
        iconEntry(Icons.payment_rounded, 'payment purchase'),
        iconEntry(Icons.credit_card_rounded, 'credit card payment'),
        iconEntry(Icons.attach_money_rounded, 'attach money price'),
        // Font Awesome
        iconEntry(FontAwesomeIcons.cartShopping, 'cart shopping'),
        iconEntry(FontAwesomeIcons.cartArrowDown, 'cart arrow down add'),
        iconEntry(FontAwesomeIcons.cartPlus, 'cart plus add'),
        iconEntry(FontAwesomeIcons.basketShopping, 'basket shopping'),
        iconEntry(FontAwesomeIcons.bagShopping, 'bag shopping'),
        iconEntry(FontAwesomeIcons.store, 'store shop'),
        iconEntry(FontAwesomeIcons.shop, 'shop store'),
        iconEntry(FontAwesomeIcons.shopLock, 'shop lock closed'),
        iconEntry(FontAwesomeIcons.shopSlash, 'shop slash closed'),
        iconEntry(FontAwesomeIcons.tag, 'tag price label'),
        iconEntry(FontAwesomeIcons.tags, 'tags price labels'),
        iconEntry(FontAwesomeIcons.barcode, 'barcode scan'),
        iconEntry(FontAwesomeIcons.qrcode, 'qr code scan'),
        iconEntry(FontAwesomeIcons.receipt, 'receipt bill'),
        iconEntry(FontAwesomeIcons.cashRegister, 'cash register'),
        iconEntry(FontAwesomeIcons.moneyBill, 'money bill cash'),
        iconEntry(FontAwesomeIcons.moneyBills, 'money bills cash'),
        iconEntry(FontAwesomeIcons.coins, 'coins money'),
        iconEntry(FontAwesomeIcons.creditCard, 'credit card payment'),
        iconEntry(FontAwesomeIcons.wallet, 'wallet money'),
        iconEntry(FontAwesomeIcons.dollarSign, 'dollar sign money'),
        iconEntry(FontAwesomeIcons.euroSign, 'euro sign money'),
        iconEntry(FontAwesomeIcons.percentage, 'percentage discount'),
        iconEntry(FontAwesomeIcons.gift, 'gift present'),
        iconEntry(FontAwesomeIcons.boxOpen, 'box open package'),
        iconEntry(FontAwesomeIcons.box, 'box package'),
        iconEntry(FontAwesomeIcons.boxes, 'boxes packages'),
        iconEntry(FontAwesomeIcons.dolly, 'dolly cart moving'),
        iconEntry(FontAwesomeIcons.truck, 'truck delivery'),
        iconEntry(FontAwesomeIcons.truckFast, 'truck fast delivery'),
        iconEntry(FontAwesomeIcons.boxesPacking, 'boxes packing shipping'),
        iconEntry(FontAwesomeIcons.peopleCarryBox, 'people carry box moving'),
        iconEntry(FontAwesomeIcons.handHolding, 'hand holding give'),
        iconEntry(FontAwesomeIcons.handHoldingDollar, 'hand holding dollar money'),
        iconEntry(FontAwesomeIcons.handHoldingHeart, 'hand holding heart donate'),
        iconEntry(FontAwesomeIcons.handshakeSimple, 'handshake simple deal'),
        iconEntry(FontAwesomeIcons.scaleBalanced, 'scale balanced justice'),
        iconEntry(FontAwesomeIcons.buildingShield, 'building shield insurance'),
        iconEntry(FontAwesomeIcons.sackDollar, 'sack dollar money'),
        iconEntry(FontAwesomeIcons.sackXmark, 'sack xmark loss'),
        iconEntry(FontAwesomeIcons.moneyBillTrendUp, 'money bill trend up profit'),
        iconEntry(FontAwesomeIcons.moneyBillTransfer, 'money bill transfer'),
        iconEntry(FontAwesomeIcons.moneyBillWheat, 'money bill wheat agriculture'),
        iconEntry(FontAwesomeIcons.moneyCheck, 'money check bank'),
        iconEntry(FontAwesomeIcons.moneyCheckDollar, 'money check dollar'),
        iconEntry(FontAwesomeIcons.stamp, 'stamp official'),
        iconEntry(FontAwesomeIcons.commentDollar, 'comment dollar price'),
      ],
    ),

    // EMOTIONS & EXPRESSIONS (50+ icons)
    IconCategory(
      name: 'Emotions',
      categoryIcon: Icons.mood_rounded,
      icons: [
        // Material
        iconEntry(Icons.mood_rounded, 'mood happy face'),
        iconEntry(Icons.mood_bad_rounded, 'mood bad sad face'),
        iconEntry(Icons.sentiment_satisfied_rounded, 'sentiment satisfied happy'),
        iconEntry(Icons.sentiment_neutral_rounded, 'sentiment neutral face'),
        iconEntry(Icons.sentiment_dissatisfied_rounded, 'sentiment dissatisfied unhappy'),
        iconEntry(Icons.emoji_emotions_rounded, 'emoji emotions face'),
        iconEntry(Icons.emoji_people_rounded, 'emoji people'),
        iconEntry(Icons.emoji_nature_rounded, 'emoji nature'),
        iconEntry(Icons.emoji_objects_rounded, 'emoji objects'),
        // Font Awesome
        iconEntry(FontAwesomeIcons.faceLaugh, 'face laugh happy'),
        iconEntry(FontAwesomeIcons.faceLaughBeam, 'face laugh beam very happy'),
        iconEntry(FontAwesomeIcons.faceGrinBeam, 'face grin beam smile'),
        iconEntry(FontAwesomeIcons.faceSmile, 'face smile happy'),
        iconEntry(FontAwesomeIcons.faceSmileBeam, 'face smile beam very happy'),
        iconEntry(FontAwesomeIcons.faceGrin, 'face grin big smile'),
        iconEntry(FontAwesomeIcons.faceGrinWide, 'face grin wide huge smile'),
        iconEntry(FontAwesomeIcons.faceGrinSquint, 'face grin squint laughing'),
        iconEntry(FontAwesomeIcons.faceGrinTears, 'face grin tears laughing crying'),
        iconEntry(FontAwesomeIcons.faceGrinStars, 'face grin stars star struck'),
        iconEntry(FontAwesomeIcons.faceKiss, 'face kiss love'),
        iconEntry(FontAwesomeIcons.faceKissBeam, 'face kiss beam love'),
        iconEntry(FontAwesomeIcons.faceKissWinkHeart, 'face kiss wink heart love'),
        iconEntry(FontAwesomeIcons.faceMeh, 'face meh neutral'),
        iconEntry(FontAwesomeIcons.faceRollingEyes, 'face rolling eyes annoyed'),
        iconEntry(FontAwesomeIcons.faceFrown, 'face frown sad'),
        iconEntry(FontAwesomeIcons.faceSadCry, 'face sad cry crying'),
        iconEntry(FontAwesomeIcons.faceSadTear, 'face sad tear crying'),
        iconEntry(FontAwesomeIcons.faceAngry, 'face angry mad'),
        iconEntry(FontAwesomeIcons.faceTired, 'face tired exhausted'),
        iconEntry(FontAwesomeIcons.faceSurprise, 'face surprise shocked'),
        iconEntry(FontAwesomeIcons.faceDizzy, 'face dizzy confused'),
        iconEntry(FontAwesomeIcons.faceGrimace, 'face grimace uncomfortable'),
        iconEntry(FontAwesomeIcons.faceFlushed, 'face flushed embarrassed'),
        iconEntry(FontAwesomeIcons.faceFrownOpen, 'face frown open sad'),
        iconEntry(FontAwesomeIcons.faceGrinSquintTears, 'face grin squint tears laughing'),
        iconEntry(FontAwesomeIcons.faceGrinHearts, 'face grin hearts love'),
        iconEntry(FontAwesomeIcons.faceGrinTongue, 'face grin tongue playful'),
        iconEntry(FontAwesomeIcons.faceGrinTongueWink, 'face grin tongue wink playful'),
        iconEntry(FontAwesomeIcons.faceGrinTongueSquint, 'face grin tongue squint playful'),
        iconEntry(FontAwesomeIcons.faceSmileWink, 'face smile wink happy'),
        iconEntry(FontAwesomeIcons.faceMehBlank, 'face meh blank expressionless'),
        iconEntry(FontAwesomeIcons.heart, 'heart love'),
        iconEntry(FontAwesomeIcons.heartCrack, 'heart crack broken heart'),
        iconEntry(FontAwesomeIcons.fire, 'fire hot excited'),
        iconEntry(FontAwesomeIcons.handsPraying, 'hands praying celebrate'),
      ],
    ),

    // TECHNOLOGY & DEVICES (80+ icons)
    IconCategory(
      name: 'Technology',
      categoryIcon: Icons.computer_rounded,
      icons: [
        // Material
        iconEntry(Icons.computer_rounded, 'computer device'),
        iconEntry(Icons.laptop_rounded, 'laptop computer'),
        iconEntry(Icons.tablet_rounded, 'tablet device'),
        iconEntry(Icons.phone_android_rounded, 'phone android mobile'),
        iconEntry(Icons.phone_iphone_rounded, 'phone iphone mobile'),
        iconEntry(Icons.watch_rounded, 'watch smartwatch'),
        iconEntry(Icons.headphones_rounded, 'headphones audio'),
        iconEntry(Icons.keyboard_rounded, 'keyboard input'),
        iconEntry(Icons.mouse_rounded, 'mouse input'),
        iconEntry(Icons.router_rounded, 'router network'),
        iconEntry(Icons.wifi_rounded, 'wifi internet'),
        iconEntry(Icons.bluetooth_rounded, 'bluetooth wireless'),
        iconEntry(Icons.usb_rounded, 'usb connection'),
        iconEntry(Icons.memory_rounded, 'memory storage'),
        iconEntry(Icons.storage_rounded, 'storage data'),
        // Font Awesome
        iconEntry(FontAwesomeIcons.laptop, 'laptop computer'),
        iconEntry(FontAwesomeIcons.laptopCode, 'laptop code programming'),
        iconEntry(FontAwesomeIcons.desktop, 'desktop computer'),
        iconEntry(FontAwesomeIcons.tablet, 'tablet device'),
        iconEntry(FontAwesomeIcons.tabletScreenButton, 'tablet screen button device'),
        iconEntry(FontAwesomeIcons.mobile, 'mobile phone'),
        iconEntry(FontAwesomeIcons.mobileScreen, 'mobile screen phone'),
        iconEntry(FontAwesomeIcons.mobileScreenButton, 'mobile screen button phone'),
        iconEntry(FontAwesomeIcons.appleWhole, 'apple device'),
        iconEntry(FontAwesomeIcons.keyboard, 'keyboard input'),
        iconEntry(FontAwesomeIcons.mouse, 'mouse input'),
        iconEntry(FontAwesomeIcons.server, 'server computer'),
        iconEntry(FontAwesomeIcons.database, 'database storage'),
        iconEntry(FontAwesomeIcons.hardDrive, 'hard drive storage'),
        iconEntry(FontAwesomeIcons.floppyDisk, 'floppy disk save'),
        iconEntry(FontAwesomeIcons.microchip, 'microchip cpu'),
        iconEntry(FontAwesomeIcons.memory, 'memory ram'),
        iconEntry(FontAwesomeIcons.wifi, 'wifi internet'),
        iconEntry(FontAwesomeIcons.ethernet, 'ethernet network'),
        iconEntry(FontAwesomeIcons.bluetooth, 'bluetooth wireless'),
        iconEntry(FontAwesomeIcons.usb, 'usb connection'),
        iconEntry(FontAwesomeIcons.plug, 'plug power'),
        iconEntry(FontAwesomeIcons.powerOff, 'power off shutdown'),
        iconEntry(FontAwesomeIcons.bolt, 'bolt lightning power'),
        iconEntry(FontAwesomeIcons.batteryFull, 'battery full charged'),
        iconEntry(FontAwesomeIcons.batteryThreeQuarters, 'battery three quarters'),
        iconEntry(FontAwesomeIcons.batteryHalf, 'battery half'),
        iconEntry(FontAwesomeIcons.batteryQuarter, 'battery quarter low'),
        iconEntry(FontAwesomeIcons.batteryEmpty, 'battery empty dead'),
        iconEntry(FontAwesomeIcons.print, 'print printer'),
        iconEntry(FontAwesomeIcons.fax, 'fax machine'),
        iconEntry(FontAwesomeIcons.sdCard, 'sd card storage'),
        iconEntry(FontAwesomeIcons.simCard, 'sim card mobile'),
        iconEntry(FontAwesomeIcons.tv, 'tv television'),
        iconEntry(FontAwesomeIcons.headphones, 'headphones audio'),
        iconEntry(FontAwesomeIcons.headset, 'headset audio'),
        iconEntry(FontAwesomeIcons.earListen, 'ear listen audio'),
        iconEntry(FontAwesomeIcons.microphone, 'microphone audio input'),
        iconEntry(FontAwesomeIcons.camera, 'camera photo'),
        iconEntry(FontAwesomeIcons.video, 'video camera'),
        iconEntry(FontAwesomeIcons.gamepad, 'gamepad gaming controller'),
        iconEntry(FontAwesomeIcons.headset, 'headset vr virtual reality'),
        iconEntry(FontAwesomeIcons.hdd, 'hdd hard disk drive'),
        iconEntry(FontAwesomeIcons.cloudArrowUp, 'cloud arrow up upload'),
        iconEntry(FontAwesomeIcons.cloudArrowDown, 'cloud arrow down download'),
        iconEntry(FontAwesomeIcons.satellite, 'satellite signal'),
        iconEntry(FontAwesomeIcons.satelliteDish, 'satellite dish'),
        iconEntry(FontAwesomeIcons.towerBroadcast, 'tower broadcast signal'),
        iconEntry(FontAwesomeIcons.towerCell, 'tower cell mobile signal'),
        iconEntry(FontAwesomeIcons.robot, 'robot ai'),
        iconEntry(FontAwesomeIcons.code, 'code programming'),
        iconEntry(FontAwesomeIcons.codeBranch, 'code branch git'),
        iconEntry(FontAwesomeIcons.terminal, 'terminal command line'),
        iconEntry(FontAwesomeIcons.windowMaximize, 'window maximize'),
        iconEntry(FontAwesomeIcons.windowMinimize, 'window minimize'),
        iconEntry(FontAwesomeIcons.windowRestore, 'window restore'),
      ],
    ),

    // SPIRITUAL & RELIGIOUS (100+ icons)
    IconCategory(
      name: 'Spiritual',
      categoryIcon: Icons.church_rounded,
      icons: [
        // Material Icons
        iconEntry(Icons.church_rounded, 'church worship religious'),
        iconEntry(Icons.temple_buddhist_rounded, 'temple buddhist religious'),
        iconEntry(Icons.temple_hindu_rounded, 'temple hindu religious'),
        iconEntry(Icons.mosque_rounded, 'mosque islamic religious'),
        iconEntry(Icons.synagogue_rounded, 'synagogue jewish religious'),
        // Font Awesome Icons - Christianity
        iconEntry(FontAwesomeIcons.church, 'church christian worship'),
        iconEntry(FontAwesomeIcons.cross, 'cross christian symbol'),
        iconEntry(FontAwesomeIcons.bookBible, 'book bible christian'),
        iconEntry(FontAwesomeIcons.placeOfWorship, 'place of worship religious'),
        iconEntry(FontAwesomeIcons.dove, 'dove peace holy spirit'),
        iconEntry(FontAwesomeIcons.handsPraying, 'hands praying prayer worship'),
        iconEntry(FontAwesomeIcons.personPraying, 'person praying prayer worship'),
        iconEntry(FontAwesomeIcons.handsHoldingCircle, 'hands holding circle prayer'),
        iconEntry(FontAwesomeIcons.handHoldingHeart, 'hand holding heart love charity'),
        iconEntry(FontAwesomeIcons.heart, 'heart love faith'),
        iconEntry(FontAwesomeIcons.ankh, 'ankh religious egyptian'),
        iconEntry(FontAwesomeIcons.gopuram, 'gopuram hindu temple'),
        // Islam
        iconEntry(FontAwesomeIcons.mosque, 'mosque islamic worship'),
        iconEntry(FontAwesomeIcons.kaaba, 'kaaba mecca islamic'),
        iconEntry(FontAwesomeIcons.bookQuran, 'book quran islamic'),
        iconEntry(FontAwesomeIcons.starAndCrescent, 'star and crescent islamic'),
        iconEntry(FontAwesomeIcons.prayingHands, 'praying hands prayer'),
        iconEntry(FontAwesomeIcons.moon, 'moon islamic ramadan'),
        iconEntry(FontAwesomeIcons.starHalfStroke, 'star half crescent'),
        // Judaism
        iconEntry(FontAwesomeIcons.starOfDavid, 'star of david jewish'),
        iconEntry(FontAwesomeIcons.bookTanakh, 'book tanakh torah jewish'),
        iconEntry(FontAwesomeIcons.menorah, 'menorah jewish hannukah'),
        // Buddhism & Hinduism
        iconEntry(FontAwesomeIcons.om, 'om hindu buddhist symbol'),
        iconEntry(FontAwesomeIcons.dharmachakra, 'dharmachakra buddhist wheel'),
        iconEntry(FontAwesomeIcons.peace, 'peace symbol'),
        iconEntry(FontAwesomeIcons.spa, 'spa meditation zen'),
        iconEntry(FontAwesomeIcons.leaf, 'leaf nature spiritual'),
        iconEntry(FontAwesomeIcons.seedling, 'seedling growth spiritual'),
        // General Spiritual
        iconEntry(FontAwesomeIcons.handsHolding, 'hands holding giving'),
        iconEntry(FontAwesomeIcons.handHoldingHand, 'hand holding hand help'),
        iconEntry(FontAwesomeIcons.handHoldingDollar, 'hand holding dollar charity donation'),
        iconEntry(FontAwesomeIcons.handHoldingDroplet, 'hand holding droplet charity'),
        iconEntry(FontAwesomeIcons.donate, 'donate charity giving'),
        iconEntry(FontAwesomeIcons.gift, 'gift giving charity'),
        iconEntry(FontAwesomeIcons.ribbon, 'ribbon awareness'),
        iconEntry(FontAwesomeIcons.circleNotch, 'circle notch meditation'),
        iconEntry(FontAwesomeIcons.sun, 'sun light divine'),
        iconEntry(FontAwesomeIcons.cloudSun, 'cloud sun heaven'),
        iconEntry(FontAwesomeIcons.mountain, 'mountain spiritual journey'),
        iconEntry(FontAwesomeIcons.water, 'water baptism spiritual'),
        iconEntry(FontAwesomeIcons.fire, 'fire holy spirit'),
        iconEntry(FontAwesomeIcons.hanukiah, 'hanukiah menorah jewish'),
        iconEntry(FontAwesomeIcons.wineGlass, 'wine glass communion'),
        iconEntry(FontAwesomeIcons.breadSlice, 'bread slice communion'),
        iconEntry(FontAwesomeIcons.book, 'book scripture holy'),
        iconEntry(FontAwesomeIcons.bookOpen, 'book open reading scripture'),
        iconEntry(FontAwesomeIcons.bookBookmark, 'book bookmark scripture'),
        iconEntry(FontAwesomeIcons.scroll, 'scroll ancient scripture'),
        iconEntry(FontAwesomeIcons.feather, 'feather angel spiritual'),
        iconEntry(FontAwesomeIcons.cloudArrowUp, 'cloud arrow up ascension heaven'),
        iconEntry(FontAwesomeIcons.handsAslInterpreting, 'hands asl worship'),
        iconEntry(FontAwesomeIcons.user, 'user person soul'),
        iconEntry(FontAwesomeIcons.users, 'users congregation community'),
        iconEntry(FontAwesomeIcons.peopleGroup, 'people group fellowship'),
        iconEntry(FontAwesomeIcons.handshake, 'handshake fellowship unity'),
        iconEntry(FontAwesomeIcons.circleHalfStroke, 'circle half stroke balance'),
        iconEntry(FontAwesomeIcons.infinity, 'infinity eternal eternity'),
        iconEntry(FontAwesomeIcons.atom, 'atom creation universe'),
        iconEntry(FontAwesomeIcons.globe, 'globe world mission'),
        iconEntry(FontAwesomeIcons.earthAmericas, 'earth americas mission'),
        iconEntry(FontAwesomeIcons.earthAfrica, 'earth africa mission'),
        iconEntry(FontAwesomeIcons.earthAsia, 'earth asia mission'),
        iconEntry(FontAwesomeIcons.earthEurope, 'earth europe mission'),
        iconEntry(FontAwesomeIcons.bell, 'bell church bell call'),
        iconEntry(FontAwesomeIcons.music, 'music worship hymn'),
        iconEntry(FontAwesomeIcons.microphone, 'microphone preaching testimony'),
        iconEntry(FontAwesomeIcons.calendarDays, 'calendar days sabbath holy day'),
        iconEntry(FontAwesomeIcons.calendarCheck, 'calendar check holy day'),
        iconEntry(FontAwesomeIcons.clock, 'clock prayer time'),
        iconEntry(FontAwesomeIcons.hourglass, 'hourglass time reflection'),
        iconEntry(FontAwesomeIcons.compass, 'compass direction guidance'),
        iconEntry(FontAwesomeIcons.route, 'route path journey'),
        iconEntry(FontAwesomeIcons.mapLocationDot, 'map location pilgrimage'),
        iconEntry(FontAwesomeIcons.ring, 'ring marriage covenant'),
        iconEntry(FontAwesomeIcons.baby, 'baby baptism dedication'),
        iconEntry(FontAwesomeIcons.cakeCandles, 'cake candles celebration'),
        iconEntry(FontAwesomeIcons.graduationCap, 'graduation cap confirmation'),
      ],
    ),

    // HOBBIES & ACTIVITIES (80+ icons)
    IconCategory(
      name: 'Hobbies',
      categoryIcon: Icons.palette_rounded,
      icons: [
        // Material Icons
        iconEntry(Icons.palette_rounded, 'palette art painting'),
        iconEntry(Icons.brush_rounded, 'brush painting art'),
        iconEntry(Icons.draw_rounded, 'draw art sketch'),
        iconEntry(Icons.colorize_rounded, 'colorize art'),
        iconEntry(Icons.photo_camera_rounded, 'photo camera photography'),
        iconEntry(Icons.camera_alt_rounded, 'camera alt photography'),
        iconEntry(Icons.videocam_rounded, 'video cam filming'),
        iconEntry(Icons.music_note_rounded, 'music note'),
        iconEntry(Icons.piano_rounded, 'piano music'),
        iconEntry(Icons.sports_esports_rounded, 'sports esports gaming'),
        iconEntry(Icons.casino_rounded, 'casino gambling gaming'),
        iconEntry(Icons.theater_comedy_rounded, 'theater comedy drama'),
        iconEntry(Icons.movie_filter_rounded, 'movie filter cinema'),
        // Font Awesome - Arts & Crafts
        iconEntry(FontAwesomeIcons.paintbrush, 'paintbrush art painting'),
        iconEntry(FontAwesomeIcons.palette, 'palette art colors'),
        iconEntry(FontAwesomeIcons.brush, 'brush art painting'),
        iconEntry(FontAwesomeIcons.sprayCanSparkles, 'spray can sparkles graffiti'),
        iconEntry(FontAwesomeIcons.pen, 'pen writing drawing'),
        iconEntry(FontAwesomeIcons.pencil, 'pencil drawing writing'),
        iconEntry(FontAwesomeIcons.penFancy, 'pen fancy calligraphy'),
        iconEntry(FontAwesomeIcons.penNib, 'pen nib calligraphy'),
        iconEntry(FontAwesomeIcons.feather, 'feather writing quill'),
        iconEntry(FontAwesomeIcons.stamp, 'stamp crafts'),
        iconEntry(FontAwesomeIcons.scissors, 'scissors crafts cutting'),
        iconEntry(FontAwesomeIcons.screwdriverWrench, 'screwdriver wrench diy'),
        iconEntry(FontAwesomeIcons.hammer, 'hammer diy building'),
        iconEntry(FontAwesomeIcons.wandSparkles, 'wand sparkles magic'),
        // Photography & Video
        iconEntry(FontAwesomeIcons.camera, 'camera photography'),
        iconEntry(FontAwesomeIcons.cameraRetro, 'camera retro vintage'),
        iconEntry(FontAwesomeIcons.video, 'video filming'),
        iconEntry(FontAwesomeIcons.film, 'film movie making'),
        iconEntry(FontAwesomeIcons.clapperboard, 'clapperboard movie'),
        iconEntry(FontAwesomeIcons.image, 'image photo'),
        iconEntry(FontAwesomeIcons.images, 'images photos gallery'),
        iconEntry(FontAwesomeIcons.photoFilm, 'photo film media'),
        // Music & Performance
        iconEntry(FontAwesomeIcons.music, 'music hobby'),
        iconEntry(FontAwesomeIcons.guitar, 'guitar music'),
        iconEntry(FontAwesomeIcons.drum, 'drum music'),
        iconEntry(FontAwesomeIcons.drumSteelpan, 'drum steelpan music'),
        iconEntry(FontAwesomeIcons.recordVinyl, 'record vinyl music'),
        iconEntry(FontAwesomeIcons.compactDisc, 'compact disc music'),
        iconEntry(FontAwesomeIcons.headphones, 'headphones music listening'),
        iconEntry(FontAwesomeIcons.microphone, 'microphone singing karaoke'),
        iconEntry(FontAwesomeIcons.masksTheater, 'masks theater drama'),
        // Gaming & Entertainment
        iconEntry(FontAwesomeIcons.gamepad, 'gamepad gaming'),
        iconEntry(FontAwesomeIcons.dice, 'dice games'),
        iconEntry(FontAwesomeIcons.diceD20, 'dice d20 rpg gaming'),
        iconEntry(FontAwesomeIcons.chessPawn, 'chess pawn board game'),
        iconEntry(FontAwesomeIcons.chessKnight, 'chess knight board game'),
        iconEntry(FontAwesomeIcons.chessBishop, 'chess bishop board game'),
        iconEntry(FontAwesomeIcons.chessRook, 'chess rook board game'),
        iconEntry(FontAwesomeIcons.chessQueen, 'chess queen board game'),
        iconEntry(FontAwesomeIcons.chessKing, 'chess king board game'),
        iconEntry(FontAwesomeIcons.chessBoard, 'chess board game'),
        iconEntry(FontAwesomeIcons.puzzlePiece, 'puzzle piece hobby'),
        iconEntry(FontAwesomeIcons.cubes, 'cubes building blocks'),
        // Reading & Writing
        iconEntry(FontAwesomeIcons.book, 'book reading'),
        iconEntry(FontAwesomeIcons.bookOpen, 'book open reading'),
        iconEntry(FontAwesomeIcons.newspaper, 'newspaper reading'),
        iconEntry(FontAwesomeIcons.bookJournalWhills, 'book journal writing'),
        iconEntry(FontAwesomeIcons.fileLines, 'file lines writing'),
        iconEntry(FontAwesomeIcons.featherPointed, 'feather pointed writing'),
        // Collecting
        iconEntry(FontAwesomeIcons.coins, 'coins collecting numismatics'),
        iconEntry(FontAwesomeIcons.stamp, 'stamp philately collecting'),
        iconEntry(FontAwesomeIcons.gem, 'gem collecting rocks'),
        iconEntry(FontAwesomeIcons.box, 'box collecting storage'),
        iconEntry(FontAwesomeIcons.archive, 'archive collecting storage'),
        // Outdoor Activities
        iconEntry(FontAwesomeIcons.personHiking, 'person hiking outdoor'),
        iconEntry(FontAwesomeIcons.personBiking, 'person biking cycling'),
        iconEntry(FontAwesomeIcons.binoculars, 'binoculars bird watching'),
        iconEntry(FontAwesomeIcons.campground, 'campground camping'),
        iconEntry(FontAwesomeIcons.tent, 'tent camping'),
        iconEntry(FontAwesomeIcons.fire, 'fire campfire'),
        iconEntry(FontAwesomeIcons.fishFins, 'fish fins fishing'),
        iconEntry(FontAwesomeIcons.personSkiing, 'person skiing'),
        iconEntry(FontAwesomeIcons.personSnowboarding, 'person snowboarding'),
        iconEntry(FontAwesomeIcons.mountain, 'mountain climbing hiking'),
      ],
    ),

    // FINANCE & MONEY (120+ icons)
    IconCategory(
      name: 'Finance',
      categoryIcon: Icons.attach_money_rounded,
      icons: [
        // Material Icons
        iconEntry(Icons.attach_money_rounded, 'attach money finance'),
        iconEntry(Icons.euro_rounded, 'euro currency finance'),
        iconEntry(Icons.currency_pound_rounded, 'currency pound finance'),
        iconEntry(Icons.currency_rupee_rounded, 'currency rupee finance'),
        iconEntry(Icons.currency_yen_rounded, 'currency yen finance'),
        iconEntry(Icons.monetization_on_rounded, 'monetization on finance'),
        iconEntry(Icons.payments_rounded, 'payments finance'),
        iconEntry(Icons.account_balance_rounded, 'account balance bank'),
        iconEntry(Icons.account_balance_wallet_rounded, 'account balance wallet'),
        iconEntry(Icons.savings_rounded, 'savings money'),
        iconEntry(Icons.trending_up_rounded, 'trending up profit'),
        iconEntry(Icons.trending_down_rounded, 'trending down loss'),
        iconEntry(Icons.show_chart_rounded, 'show chart stocks'),
        iconEntry(Icons.pie_chart_rounded, 'pie chart budget'),
        // Font Awesome - Currency
        iconEntry(FontAwesomeIcons.dollarSign, 'dollar sign usd'),
        iconEntry(FontAwesomeIcons.euroSign, 'euro sign eur'),
        iconEntry(FontAwesomeIcons.sterlingSign, 'sterling sign gbp pound'),
        iconEntry(FontAwesomeIcons.yenSign, 'yen sign jpy'),
        iconEntry(FontAwesomeIcons.indianRupeeSign, 'indian rupee sign inr'),
        iconEntry(FontAwesomeIcons.wonSign, 'won sign krw'),
        iconEntry(FontAwesomeIcons.bitcoinSign, 'bitcoin sign btc crypto'),
        iconEntry(FontAwesomeIcons.nairaSign, 'naira sign ngn'),
        iconEntry(FontAwesomeIcons.pesoSign, 'peso sign mxn'),
        iconEntry(FontAwesomeIcons.rubleSign, 'ruble sign rub'),
        iconEntry(FontAwesomeIcons.turkishLiraSign, 'turkish lira sign try'),
        iconEntry(FontAwesomeIcons.bahtSign, 'baht sign thb'),
        iconEntry(FontAwesomeIcons.liraSign, 'lira sign itl'),
        iconEntry(FontAwesomeIcons.australSign, 'austral sign ars'),
        iconEntry(FontAwesomeIcons.cruzeiroSign, 'cruzeiro sign brc'),
        iconEntry(FontAwesomeIcons.francSign, 'franc sign chf'),
        iconEntry(FontAwesomeIcons.guaraniSign, 'guarani sign pyg'),
        iconEntry(FontAwesomeIcons.kipSign, 'kip sign lak'),
        iconEntry(FontAwesomeIcons.manatSign, 'manat sign azn'),
        iconEntry(FontAwesomeIcons.millSign, 'mill sign'),
        // Money & Banking
        iconEntry(FontAwesomeIcons.moneyBill, 'money bill cash'),
        iconEntry(FontAwesomeIcons.moneyBills, 'money bills cash'),
        iconEntry(FontAwesomeIcons.moneyBillWave, 'money bill wave cash'),
        iconEntry(FontAwesomeIcons.moneyBillTransfer, 'money bill transfer payment'),
        iconEntry(FontAwesomeIcons.moneyBillTrendUp, 'money bill trend up profit'),
        iconEntry(FontAwesomeIcons.moneyCheck, 'money check bank'),
        iconEntry(FontAwesomeIcons.moneyCheckDollar, 'money check dollar'),
        iconEntry(FontAwesomeIcons.coins, 'coins money change'),
        iconEntry(FontAwesomeIcons.piggyBank, 'piggy bank savings'),
        iconEntry(FontAwesomeIcons.wallet, 'wallet money'),
        iconEntry(FontAwesomeIcons.sackDollar, 'sack dollar money bag'),
        iconEntry(FontAwesomeIcons.sackXmark, 'sack xmark loss debt'),
        iconEntry(FontAwesomeIcons.cashRegister, 'cash register'),
        iconEntry(FontAwesomeIcons.creditCard, 'credit card payment'),
        iconEntry(FontAwesomeIcons.buildingColumns, 'building columns bank'),
        iconEntry(FontAwesomeIcons.landmark, 'landmark institution bank'),
        iconEntry(FontAwesomeIcons.vault, 'vault safe bank'),
        iconEntry(FontAwesomeIcons.stamp, 'stamp official document'),
        // Payments & Transactions
        iconEntry(FontAwesomeIcons.circleDollarToSlot, 'circle dollar to slot donate'),
        iconEntry(FontAwesomeIcons.handHoldingDollar, 'hand holding dollar payment'),
        iconEntry(FontAwesomeIcons.commentDollar, 'comment dollar pricing'),
        iconEntry(FontAwesomeIcons.receipt, 'receipt bill invoice'),
        iconEntry(FontAwesomeIcons.fileInvoice, 'file invoice billing'),
        iconEntry(FontAwesomeIcons.fileInvoiceDollar, 'file invoice dollar'),
        iconEntry(FontAwesomeIcons.ccVisa, 'cc visa credit card'),
        iconEntry(FontAwesomeIcons.ccMastercard, 'cc mastercard credit card'),
        iconEntry(FontAwesomeIcons.ccAmex, 'cc amex credit card'),
        iconEntry(FontAwesomeIcons.ccPaypal, 'cc paypal payment'),
        iconEntry(FontAwesomeIcons.ccStripe, 'cc stripe payment'),
        iconEntry(FontAwesomeIcons.ccAmazonPay, 'cc amazon pay payment'),
        iconEntry(FontAwesomeIcons.ccApplePay, 'cc apple pay payment'),
        iconEntry(FontAwesomeIcons.googlePay, 'google pay payment'),
        iconEntry(FontAwesomeIcons.bitcoin, 'bitcoin crypto'),
        iconEntry(FontAwesomeIcons.ethereum, 'ethereum crypto'),
        // Investment & Trading
        iconEntry(FontAwesomeIcons.chartLine, 'chart line stocks trading'),
        iconEntry(FontAwesomeIcons.chartPie, 'chart pie portfolio'),
        iconEntry(FontAwesomeIcons.chartColumn, 'chart column analysis'),
        iconEntry(FontAwesomeIcons.arrowTrendUp, 'arrow trend up growth'),
        iconEntry(FontAwesomeIcons.arrowTrendDown, 'arrow trend down decline'),
        iconEntry(FontAwesomeIcons.scaleBalanced, 'scale balanced balance sheet'),
        iconEntry(FontAwesomeIcons.percentage, 'percentage interest rate'),
        iconEntry(FontAwesomeIcons.calculator, 'calculator accounting'),
        iconEntry(FontAwesomeIcons.chartGantt, 'chart gantt planning'),
        iconEntry(FontAwesomeIcons.briefcase, 'briefcase business finance'),
        iconEntry(FontAwesomeIcons.handshake, 'handshake deal agreement'),
        iconEntry(FontAwesomeIcons.signature, 'signature contract'),
        iconEntry(FontAwesomeIcons.fileContract, 'file contract agreement'),
        iconEntry(FontAwesomeIcons.stamp, 'stamp certified'),
        iconEntry(FontAwesomeIcons.shield, 'shield insurance protection'),
        iconEntry(FontAwesomeIcons.shieldHalved, 'shield halved security'),
        iconEntry(FontAwesomeIcons.lock, 'lock secure finance'),
        iconEntry(FontAwesomeIcons.key, 'key access security'),
        iconEntry(FontAwesomeIcons.userSecret, 'user secret private banking'),
        iconEntry(FontAwesomeIcons.eye, 'eye view monitor'),
        iconEntry(FontAwesomeIcons.eyeSlash, 'eye slash hidden private'),
      ],
    ),

    // SCIENCE & SPACE (80+ icons)
    IconCategory(
      name: 'Science',
      categoryIcon: Icons.science_rounded,
      icons: [
        // Material Icons
        iconEntry(Icons.science_rounded, 'science lab chemistry'),
        iconEntry(Icons.biotech_rounded, 'biotech biology'),
        iconEntry(Icons.psychology_rounded, 'psychology brain science'),
        iconEntry(Icons.psychology_alt_rounded, 'psychology alt brain'),
        iconEntry(Icons.rocket_launch_rounded, 'rocket launch space'),
        iconEntry(Icons.satellite_rounded, 'satellite space'),
        iconEntry(Icons.satellite_alt_rounded, 'satellite alt space'),
        // Font Awesome - Laboratory
        iconEntry(FontAwesomeIcons.flask, 'flask lab chemistry'),
        iconEntry(FontAwesomeIcons.flaskVial, 'flask vial lab experiment'),
        iconEntry(FontAwesomeIcons.vial, 'vial lab test'),
        iconEntry(FontAwesomeIcons.vialCircleCheck, 'vial circle check test results'),
        iconEntry(FontAwesomeIcons.vialVirus, 'vial virus virology'),
        iconEntry(FontAwesomeIcons.vials, 'vials lab tests'),
        iconEntry(FontAwesomeIcons.microscope, 'microscope lab biology'),
        iconEntry(FontAwesomeIcons.atom, 'atom physics chemistry'),
        iconEntry(FontAwesomeIcons.dna, 'dna genetics biology'),
        iconEntry(FontAwesomeIcons.brain, 'brain neuroscience'),
        iconEntry(FontAwesomeIcons.heartPulse, 'heart pulse cardiology'),
        iconEntry(FontAwesomeIcons.lungs, 'lungs pulmonology'),
        iconEntry(FontAwesomeIcons.virus, 'virus virology'),
        iconEntry(FontAwesomeIcons.disease, 'disease pathology'),
        iconEntry(FontAwesomeIcons.syringe, 'syringe injection'),
        iconEntry(FontAwesomeIcons.pills, 'pills pharmacology'),
        iconEntry(FontAwesomeIcons.capsules, 'capsules medicine'),
        iconEntry(FontAwesomeIcons.prescription, 'prescription pharmacy'),
        // Space & Astronomy
        iconEntry(FontAwesomeIcons.rocket, 'rocket space'),
        iconEntry(FontAwesomeIcons.shuttleSpace, 'shuttle space spacecraft'),
        iconEntry(FontAwesomeIcons.satellite, 'satellite space'),
        iconEntry(FontAwesomeIcons.satelliteDish, 'satellite dish antenna'),
        iconEntry(FontAwesomeIcons.meteor, 'meteor space'),
        iconEntry(FontAwesomeIcons.moon, 'moon astronomy'),
        iconEntry(FontAwesomeIcons.sun, 'sun astronomy'),
        iconEntry(FontAwesomeIcons.cloudMoon, 'cloud moon night sky'),
        iconEntry(FontAwesomeIcons.cloudSun, 'cloud sun day sky'),
        iconEntry(FontAwesomeIcons.starAndCrescent, 'star and crescent astronomy'),
        iconEntry(FontAwesomeIcons.star, 'star astronomy'),
        iconEntry(FontAwesomeIcons.userAstronaut, 'user astronaut space'),
        iconEntry(FontAwesomeIcons.globe, 'globe earth planet'),
        iconEntry(FontAwesomeIcons.earthAmericas, 'earth americas planet'),
        iconEntry(FontAwesomeIcons.earthAfrica, 'earth africa planet'),
        iconEntry(FontAwesomeIcons.earthAsia, 'earth asia planet'),
        iconEntry(FontAwesomeIcons.earthEurope, 'earth europe planet'),
        iconEntry(FontAwesomeIcons.earthOceania, 'earth oceania planet'),
        // Physics & Math
        iconEntry(FontAwesomeIcons.magnet, 'magnet physics'),
        iconEntry(FontAwesomeIcons.bolt, 'bolt electricity physics'),
        iconEntry(FontAwesomeIcons.fire, 'fire thermodynamics'),
        iconEntry(FontAwesomeIcons.snowflake, 'snowflake cryogenics'),
        iconEntry(FontAwesomeIcons.droplet, 'droplet fluid dynamics'),
        iconEntry(FontAwesomeIcons.wind, 'wind aerodynamics'),
        iconEntry(FontAwesomeIcons.circleRadiation, 'circle radiation nuclear'),
        iconEntry(FontAwesomeIcons.radiation, 'radiation nuclear physics'),
        iconEntry(FontAwesomeIcons.biohazard, 'biohazard safety biology'),
        iconEntry(FontAwesomeIcons.triangleExclamation, 'triangle exclamation warning'),
        iconEntry(FontAwesomeIcons.calculator, 'calculator mathematics'),
        iconEntry(FontAwesomeIcons.squareRootVariable, 'square root variable math'),
        iconEntry(FontAwesomeIcons.infinity, 'infinity mathematics'),
        iconEntry(FontAwesomeIcons.equals, 'equals mathematics'),
        iconEntry(FontAwesomeIcons.notEqual, 'not equal mathematics'),
        iconEntry(FontAwesomeIcons.greaterThan, 'greater than mathematics'),
        iconEntry(FontAwesomeIcons.lessThan, 'less than mathematics'),
        iconEntry(FontAwesomeIcons.percent, 'percent mathematics'),
        iconEntry(FontAwesomeIcons.divide, 'divide mathematics'),
        iconEntry(FontAwesomeIcons.plus, 'plus mathematics add'),
        iconEntry(FontAwesomeIcons.minus, 'minus mathematics subtract'),
        iconEntry(FontAwesomeIcons.xmark, 'xmark mathematics multiply'),
        // Tools & Equipment
        iconEntry(FontAwesomeIcons.ruler, 'ruler measurement'),
        iconEntry(FontAwesomeIcons.rulerCombined, 'ruler combined measurement'),
        iconEntry(FontAwesomeIcons.compass, 'compass geometry'),
        iconEntry(FontAwesomeIcons.compassDrafting, 'compass drafting geometry'),
        iconEntry(FontAwesomeIcons.magnifyingGlass, 'magnifying glass research'),
        iconEntry(FontAwesomeIcons.magnifyingGlassPlus, 'magnifying glass plus zoom'),
        iconEntry(FontAwesomeIcons.clipboard, 'clipboard research notes'),
        iconEntry(FontAwesomeIcons.clipboardCheck, 'clipboard check experiment'),
      ],
    ),

    // WEATHER & SEASONS (60+ icons)
    IconCategory(
      name: 'Weather',
      categoryIcon: Icons.wb_sunny_rounded,
      icons: [
        // Material Icons
        iconEntry(Icons.wb_sunny_rounded, 'wb sunny sun weather'),
        iconEntry(Icons.wb_cloudy_rounded, 'wb cloudy weather'),
        iconEntry(Icons.cloud_rounded, 'cloud weather'),
        iconEntry(Icons.cloud_queue_rounded, 'cloud queue weather'),
        iconEntry(Icons.cloud_off_rounded, 'cloud off clear'),
        iconEntry(Icons.thunderstorm_rounded, 'thunderstorm weather'),
        iconEntry(Icons.grain_rounded, 'grain rain weather'),
        iconEntry(Icons.ac_unit_rounded, 'ac unit snow weather'),
        iconEntry(Icons.severe_cold_rounded, 'severe cold weather'),
        iconEntry(Icons.wind_power_rounded, 'wind power weather'),
        iconEntry(Icons.tornado_rounded, 'tornado weather'),
        iconEntry(Icons.tsunami_rounded, 'tsunami weather'),
        iconEntry(Icons.flood_rounded, 'flood weather'),
        iconEntry(Icons.beach_access_rounded, 'beach access sunny'),
        iconEntry(Icons.umbrella_rounded, 'umbrella rain weather'),
        // Font Awesome
        iconEntry(FontAwesomeIcons.sun, 'sun sunny clear'),
        iconEntry(FontAwesomeIcons.moon, 'moon night clear'),
        iconEntry(FontAwesomeIcons.cloudSun, 'cloud sun partly cloudy'),
        iconEntry(FontAwesomeIcons.cloudMoon, 'cloud moon partly cloudy night'),
        iconEntry(FontAwesomeIcons.cloud, 'cloud cloudy overcast'),
        iconEntry(FontAwesomeIcons.cloudRain, 'cloud rain rainy'),
        iconEntry(FontAwesomeIcons.cloudShowersHeavy, 'cloud showers heavy rain'),
        iconEntry(FontAwesomeIcons.cloudShowersWater, 'cloud showers water rain'),
        iconEntry(FontAwesomeIcons.cloudBolt, 'cloud bolt thunderstorm'),
        iconEntry(FontAwesomeIcons.cloudMeatball, 'cloud meatball hail'),
        iconEntry(FontAwesomeIcons.snowflake, 'snowflake snow winter'),
        iconEntry(FontAwesomeIcons.icicles, 'icicles cold frozen'),
        iconEntry(FontAwesomeIcons.wind, 'wind windy breezy'),
        iconEntry(FontAwesomeIcons.tornado, 'tornado cyclone'),
        iconEntry(FontAwesomeIcons.hurricane, 'hurricane storm'),
        iconEntry(FontAwesomeIcons.smog, 'smog fog pollution'),
        iconEntry(FontAwesomeIcons.rainbow, 'rainbow weather'),
        iconEntry(FontAwesomeIcons.umbrella, 'umbrella rain'),
        iconEntry(FontAwesomeIcons.pooStorm, 'poo storm weather'),
        iconEntry(FontAwesomeIcons.temperatureHigh, 'temperature high hot'),
        iconEntry(FontAwesomeIcons.temperatureLow, 'temperature low cold'),
        iconEntry(FontAwesomeIcons.temperatureArrowUp, 'temperature arrow up warming'),
        iconEntry(FontAwesomeIcons.temperatureArrowDown, 'temperature arrow down cooling'),
        iconEntry(FontAwesomeIcons.temperatureHalf, 'temperature half moderate'),
        iconEntry(FontAwesomeIcons.thermometer, 'thermometer temperature'),
        iconEntry(FontAwesomeIcons.fire, 'fire hot heat'),
        iconEntry(FontAwesomeIcons.droplet, 'droplet water rain'),
        iconEntry(FontAwesomeIcons.water, 'water rain flood'),
        // Seasons
        iconEntry(FontAwesomeIcons.seedling, 'seedling spring'),
        iconEntry(FontAwesomeIcons.leaf, 'leaf autumn fall'),
        iconEntry(FontAwesomeIcons.tree, 'tree forest nature'),
        iconEntry(FontAwesomeIcons.snowman, 'snowman winter'),
        iconEntry(FontAwesomeIcons.snowplow, 'snowplow winter'),
        iconEntry(FontAwesomeIcons.icicles, 'icicles winter frost'),
        iconEntry(FontAwesomeIcons.umbrellaBeach, 'umbrella beach summer'),
        iconEntry(FontAwesomeIcons.personSwimming, 'person swimming summer'),
        iconEntry(FontAwesomeIcons.iceCream, 'ice cream summer'),
      ],
    ),
  ];

  static List<IconEntry> get allIcons {
    return categories.expand((category) => category.icons).toList();
  }
}
